### PR TITLE
Removed unneeded vars - fixed logical condition

### PR DESCRIPTION
**Pull request by svilex**

### CODE REVIEW

**Comment by svilex** [comment]
I think there are floating point inaccuracy problems here:

sometimes `$diffY` isn't the same as `-$dy` .

**Comment by dktapps** [comment]
It's been reverted, the commit caused some movement issues.

**Comment by SOF3** [comment]
@svilex I think `$a - $b` and `-($b - $a)` always give the same floating point result.

**Comment by svilex** [comment]
@SOF3 That's what i tought but , try using a `var_dump()`

**Pull request merged**
