### PR TITLE
Fix for #4680 - /kill not actually killing

### LINKED ISSUE #4680: /kill command doesn’t kill the player directly
### Issue description

- Expected result: The player should directly die.
- Actual result: The player takes 500 hearts of damage.

### Steps to reproduce the issue
1. Give yourself max level (255) health boost or absorption with /effect
2. Execute /kill
3. Notice that you only took damage

### OS and versions

* PocketMine-MP: 4.0.0 (git hash: 468faa464b2bc5c97f23fafbb71ea61035f6f218)
* PHP: 8.0.12
* Using JIT: no 
* Server OS: linux
* Game version: iOS

### Plugins
This issue can be reproduced without plugins.

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/58715544/147520799-5e7c24a9-c2f0-4337-88c3-31653abbd7ad.mp4

### PR DESCRIPTION
**Pull request by jasonw4331**
## Introduction

Fixes /kill not functioning when player had more than 1000 health

### Relevant issues

* Fixes #4680

### API changes

N/A

### Behavioral changes

/kill will now *always* kill the player

## Backwards compatibility

N/A

## Follow-up

N/A

## Tests

In-game testing with absorption 255 + regen 255 + health boost 255 + resistance 255 results in player death

### CODE REVIEW

**Comment by NTT1906** [comment]
I don't know if pm4 is developing towards bedrock or java, or mixed... but as far as I remember, bedrock' /kill only deals massive damage and doesn't remove the entity.

**Comment by jasonw4331** [comment]
I think it's best to go with what the user is expecting rather than matching either Bedrock or Java in particular. Killing the player is the expected result of using /kill, so by that logic it should be implemented this way.

**Comment by dktapps** [comment]
> I think it's best to go with what the user is expecting rather than matching either Bedrock or Java in particular. Killing the player is the expected result of using /kill, so by that logic it should be implemented this way.

+1 to this. Intuitively making sense is better than bug-for-bug parity with either version.

**Review by dktapps — COMMENTED** [review]
This is problematic since it doesn't allow plugins to intervene or intercept the event. This is a behavioural break.
That said, whether or not plugins should be able to cancel this kind of thing is up for debate.

**Comment by ghost** [comment]
$player->attack(new EntityDamageEvent($player, EntityDamageEvent::CAUSE_SUICIDE, PHP_INT_MAX));

**Pull request closed without merging**
