### PR TITLE
Hard code vanilla command's names in their __constructor

### PR DESCRIPTION
**Pull request by BrandPVP**
## Introduction
So, now all the vanilla commands pass their name from their constructor like the other things (aliases, permissions, description..)

### API changes
No

### Behavioural changes
No

## Backwards compatibility
BC break, I think?

### CODE REVIEW

**Comment by SOF3** [comment]
what is the motivation of this change?

**Comment by dktapps** [comment]
Consistency, I suppose? It doesn't make any sense to declare the names outside the constructor, but the aliases inside it.

That being said, I'm also doubtful that this provides any meaningful benefit to justify the BC break.

**Comment by jasonw4331** [comment]
Wouldn't it be better to supply translations for all these instead of hard coding the command names?

**Comment by dktapps** [comment]
No. Command names can't be translated.

**Comment by SOF3** [comment]
I wouldn't consider this to be a BC break since vanilla commands should not be part of the public API.

That said, I have been thinking about configurable command names, but in fact, command names should not be configurable, only aliases should be (see #3371 and related discussions).

**Review by SOF3 — APPROVED** [review]

**Comment by dktapps** [comment]
> That said, I have been thinking about configurable command names, but in fact, command names should not be configurable, only aliases should be (see https://github.com/pmmp/PocketMine-MP/issues/3371 and related discussions).

I've recently considered getting rid of the idea of "command name" entirely. The only real use for `Command->getName()` is with `CommandExecutor` implementors (essentially a locally unique command ID, not unique globally). Any other usage of a "primary" command alias uses `getLabel()`.

**Comment by SOF3** [comment]
Let's move that discussion to #3371 anyway. Changes to the command alias mechanism should not be a blocker for this PR.

**Pull request merged**
