### PR TITLE
Fixed use of items

### PR DESCRIPTION
**Pull request by Govdim**
After two unsuccessful attempts to solve this problem, I came to the right solution (I hope ._.)

### CODE REVIEW

**Comment by TwistedAsylumMC** [comment]
Might be better if you had like a ``Useable`` class/interface or something which returns true in that function

**Comment by Govdim** [comment]
> Might be better if you had like a `Useable` class/interface or something which returns true in that function

I think this is not a good idea :/

**Comment by TwistedAsylumMC** [comment]
Why is that?

**Comment by Govdim** [comment]
> Why is that?

Personally, it will be inconvenient for me to implement new items that perform some kind of action.

**Comment by Govdim** [comment]
And what about bow, crossbow and other tools? How will it look like?

**Pull request closed without merging**
