### PR TITLE
Kick on ban.

### PR DESCRIPTION
**Pull request by Dog2puppy**
If you ban a user using a plugin, the user can continue to play even though they're banned. This fixes that by kicking the player. This Pull Request also changes the /ban command so that it no longer handles the kick because it's now handled by the ban function.

### CODE REVIEW

**Comment by jojoe77777** [comment]
$target is/(can be?) the player's name.

**Comment by Dog2puppy** [comment]
@jojoe77777 Opps. Should fix that.

**Comment by jojoe77777** [comment]
@Dog2puppy but the player could be offline

**Comment by Dog2puppy** [comment]
@jojoe77777 Fixed.

**Pull request closed without merging**
