### PR TITLE
Implement Netherite

### PR DESCRIPTION
**Pull request by Rateek**
## Introduction
Allows to add the Netherite base on PocketMine, with the right values.

That adds the armor, the ingot, and the tools...

## Changes
Added `NetheriteHelmet`, `NetheriteChestplate`, `NetheriteLeggings`, `NetheriteBoots` class.

### API changes
No change of API.

## Backwards compatibility
This PR is compatible with all plugins.

## Tests
Proof that everything is working properly:
Screenshot_399

### CODE REVIEW

**Comment by dktapps** [comment]
Hi, the stable branch is currently in feature freeze and is soon to be dropped from support. Since it would cause me unnecessary pain to merge this into PM4 where active development is, I'm going to close this, but feel free to make a similar PR to the master branch once it supports 1.16.

**Comment by mote166** [comment]
i suggest you make a plugin for it @rateek

**Comment by lukeeey** [comment]
@mote166 well no, that is not the solution for everything

**Comment by Nu4h-dev** [comment]
If you want me and an other guys have e plugin to add the netherite armor + the pickaxe,axe,shovle,hoe ad sword

**Comment by dktapps** [comment]
Stop spamming your ads everywhere or you'll be banned from the repository.

**Pull request closed without merging**
