### PR TITLE
Added Conduit Power effect

### PR DESCRIPTION
**Pull request by moskadev**
#### **TRANSLATIONS NEEDED, DO NOT MERGE THIS PR**
This PR adds a new effect : **Conduit Power**, it increases underwater visibility and mining speed, prevents drowning.

### API changes
* Added `Effect::CONDUIT_POWER`
* Now can be added to a player with `/effect`

### Requires translations
| Name | Value in eng.ini |
| `potion.conduitPower` | Conduit Power |

## Tests
Tested, everything works. Translations are just needed.

### CODE REVIEW

**Comment by supermaxalex** [comment]
Translations will be added soon.

**Comment by Muqsit** [comment]
The underwater speed is client-sided and so is the block breaking speed (I'm assuming).
But you will want to notify the server about the block break speed change. The server uses it for calculating the block crack animation duration (see `Player::getBreakTime()`).

**Comment by lukeeey** [comment]
Wouldnt client sided underwater speed f*ck up some anticheats?

**Comment by Driesboy** [comment]
Yup, but who has water in his server ;)

Op 20-mei-2018 17:38 schreef "Luke (TheDiamondYT)" <notifications@github.com
>:

Wouldnt client sided underwater speed f*ck up some anticheats?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pmmp/PocketMine-MP/pull/2192#issuecomment-390491084>,
or mute the thread

**Comment by lukeeey** [comment]
Any survival based server ever created?

**Comment by Driesboy** [comment]
most of the survival servers are private and doesn't have an anticheat. and
the public once are big and have there own ;)

Op zo 20 mei 2018 18:36 schreef Luke (TheDiamondYT) <
notifications@github.com>:

**Comment by supermaxalex** [comment]
The wiki hasn’t got any values about the speed and mining speed, so I won’t modify anything.

**Comment by lukeeey** [comment]
I said survival-based server. That means Factions too.

**Comment by kenygamer** [comment]
is there any video of what this effect does?

**Comment by MisterSheeple** [comment]
@dktapps Are you sure? I thought they added the conduit and conduit power in 1.4.0

**Comment by supermaxalex** [comment]
@MisterSheeple I thought too, but they will come in 1.5.0.

**Comment by MCPEChicken** [comment]
conduit power isnt on bedrock edition yet... its still in the 1.5 beta

**Comment by dktapps** [comment]
The mining speed issue can be disregarded since PM doesn't account for underwater mining speed yet anyway.

As a side note, bubbles are supposed to now regenerate rapidly instead of all at once when the player is able to breathe, but that's not directly in the scope of this PR.

**Comment by dktapps** [comment]
Integrated with translations to 3.2 and master as f3b2bcfd139614f78907489cb09eeb65d494fbea. Thanks!

**Pull request closed without merging**
