### PR TITLE
Ignore Hotbar Slots with Air

### PR DESCRIPTION
**Pull request by junkdude**
## Introduction

This fixes drag and dropping on w10 when taking items to/from the hotbar. 

### API changes

None
### Behavioural changes

None
## Backwards compatibility

Not sure

### CODE REVIEW

**Comment by dktapps** [comment]
I'd expect some kind of explanation to demonstrate you actually have a clue what you're doing and not just hacking it.

**Comment by junkdude** [comment]
Okay, so if you try to shift-click an item from the hotbar on W10 it wont work because the air id and the $item id are two different well id's. This fixes this by ignoring empty slots or slots that have "air" in them.

**Comment by dktapps** [comment]
I'm afraid I don't see what you are driving at. Shift-clicking things in and out of the hotbar works perfectly fine.

**Comment by junkdude** [comment]
Not for me, it ends up saying tried to equip air but have diamond sword in target slot

**Comment by junkdude** [comment]
Keep in mind im on classic ui

**Comment by dktapps** [comment]
I remain unconvinced. Shift-clicking is treated just like any other inventory transaction. I cannot reproduce the bug you're talking about.

**Comment by junkdude** [comment]
My bad i meant drag and dropping

**Comment by dktapps** [comment]
That particular issue has nothing to do with this handler, it's an issue with transaction processing. This will be resolved in the 1.2 inventory rewrite.

**Comment by junkdude** [comment]
Mkay

**Pull request closed without merging**
