### PR TITLE
Fixed player can eat cake in creative mode

### PR DESCRIPTION
**Pull request by zKoz210**

### CODE REVIEW

**Comment by dktapps** [comment]
The title of this pull request is misleading. It's preferred that you describe the bug that you're fixing as opposed to the the result of the bug fix.

**Comment by dktapps** [comment]
I'm unable to reproduce the bug described here. Please give reproducing steps.

**Comment by zKoz210** [comment]
1. 
image

2. /gamemode 1
3. Tap to Cake

**Comment by dktapps** [comment]
This would appear to affect all eatable items. The only reason the same bug does not affect normal foods is because the client doesn't send the eating action for those.

**Pull request closed without merging**
