### PR TITLE
Add all entity ids

### PR DESCRIPTION
**Pull request by Matze997**
## Introduction
This pull request aims to add all minecraft entity ids

### Relevant issues
N/A

## Changes
- Added all entity ids to AddActorPacket.php and EntityIds.php

### API changes
N/A

### Behavioural changes
N/A

## Backwards compatibility
Yes

## Follow-up
N/A

Requires translations:
N/A

## Tests

grafik
grafik
grafik

### CODE REVIEW

**Comment by SOF3** [comment]
What is the reason of adding these IDs if they are not used in PocketMine itself?

**Comment by Matze997** [comment]
Simply to make it easier for developers to spawn the new entities

**Comment by buchwasa** [comment]
> What is the reason of adding these IDs if they are not used in PocketMine itself?

If we stuck with that mindset, then the EntityIds list would be pretty empty.

**Comment by lukeeey** [comment]
The only reason I could see for this is for documentation purposes so that plugin developers can find the IDs.

I might document them on a sub page at https://wiki.vg/Bedrock_Protocol tomorrow.

**Comment by dktapps** [comment]
New numeric IDs are useless anyway.

**Comment by dktapps** [comment]
This is no longer useful since 3.13.0, since PM's AddActorPacket impl accepts string IDs.

**Pull request closed without merging**
