### PR TITLE
Fix torch placement

### PR DESCRIPTION
**Pull request by ShockedPlot7560**
## Introduction
The current version of PocketMine-MP does not allow to place the torches like Vanilla, limiting the placement only on solid blocks or barriers / walls. However, minecraft vanilla allows placement on slabs in high position / stair on top position, etc etc

### Relevant issues
* Linked #458 

### Behavioural changes
A more complete check is made on the torch support

## Follow-up
Keep up to date with the implementation of new blocks such as the composter or other unimplemented vanilla blocks

## Tests
https://user-images.githubusercontent.com/66992287/150692172-736af462-cff5-451e-b991-4bb7cb820030.mp4

### CODE REVIEW

**Comment by Govdim** [comment]
Torches cannot be placed on trapdoors. Check it out in single player.

**Comment by ShockedPlot7560** [comment]
> Torches cannot be placed on trapdoors. Check it out in single player.

indeed, I thought I had succeeded, so much for me

**Comment by dktapps** [comment]
I'm not a fan of this solution. It feels too much like a special-case hack.

What we really need is some way for blocks to indicate which of their faces are solid and/or can provide support to other blocks.

**Comment by ShockedPlot7560** [comment]
> I'm not a fan of this solution. It feels too much like a special-case hack.
> 
> What we really need is some way for blocks to indicate which of their faces are solid and/or can provide support to other blocks.

I totally agree on this point, I have thought of many other solutions. However, there are blocks that will have a solid face in one case, but in other cases, they will not accept the block.

**Comment by dktapps** [comment]
Closing in favour of #4886

**Pull request closed without merging**
