### PR TITLE
Add new mob: Bee

### PR DESCRIPTION
**Pull request by alvin0319**
## Introduction

as you know, the Minecraft 1.14 has new mob: BEE

So PocketMine-MP should be update EntityIds

### API changes

Added `const BEE = 114;` to EntityIds

Added `EntityIds::BEE => "minecraft:bee"` to AddActorPacket

Note for Developers:

width: 0.5 (not sure)
height: 0.6 (not sure)

## Tests

KakaoTalk_20191212_191952790

### CODE REVIEW

**Comment by lukeeey** [comment]
i can see this being rejected easily

**Review by TheBlackPlague — APPROVED** [review]
Looks good to me.

**Comment by dktapps** [comment]
@lukeeey perhaps you'd like to tell us why?

**Comment by CupidonSauce173** [comment]
The width and height are 0.6 (not 0.5) for adults.
Reference : https://minecraft.gamepedia.com/Bee

**Comment by lukeeey** [comment]
@dktapps I swear you usually reject simple things like adding new entities?

**Comment by lukeeey** [comment]
Nevermind it's just the ids didnt realise that

**Comment by dktapps** [comment]
I reject things that have a reason to be rejected. So far there is no obvious reason to reject this.

**Review by RandomClone — APPROVED** [review]

**Comment by dktapps** [comment]
Minecraft mobs do not have integer IDs anymore, so adding new ones at this stage is misleading to developers.

The only reason this is actually necessary is because of a poorly-thought-out backwards-compatibility hack applied to `AddActorPacket`. This problem has been resolved by c19ab976107446b629e586add9983db83496f0e6 and will be released in the upcoming 3.12.0 release.

**Pull request closed without merging**
