### PR TITLE
add GameRules const

### PR DESCRIPTION
**Pull request by Saehing**
I want to add GameRules const

### CODE REVIEW

**Comment by DenielWorld** [comment]
What are you doing? You literally opened this PR twice before with the same message and closed them. Stop spamming the PRs if you do not have any serious intentions :/

**Comment by DenielWorld** [comment]
What are you doing? You literally opened this PR twice before with the same message and closed them. Stop spamming the PRs if you do not have any serious intentions :/

**Comment by Saehing** [comment]
> What are you doing? You literally opened this PR twice before with the same message and closed them. Stop spamming the PRs if you do not have any serious intentions :/

I apologize for my last actions, there were gross errors in them.

**Comment by DenielWorld** [comment]
You could of added more commits rather than reopen your PRs

**Comment by Saehing** [comment]
> You could of added more commits rather than reopen your PRs

Sorry, in the system of GitHub, I'm still a newbie

**Comment by DenielWorld** [comment]
Google then ;v

**Comment by Saehing** [comment]
> Google then ;v

Yes, absolutely, but I'm still learning :)

**Comment by DenielWorld** [comment]
Well yeah that's the point, when you are unsure about something google it

**Comment by Saehing** [comment]
> Well yeah that's the point, when you are unsure about something google it

Apparently I really offended you, I'm sorry

**Comment by DenielWorld** [comment]
Not quite, I just want people to know what they are doing. It seems that you in fact did not have any bad intentions, I apologize from my side as well.

**Comment by Saehing** [comment]
> Not quite, I just want people to know what they are doing. It seems that you in fact did not have any bad intentions, I apologize from my side as well.

I'm glad that everything is clear. Though I do not know how to use GitHub, but totally want to help the team of pmmp. 

Sorry for my English, I use another language.

Thanks

**Comment by SOF3** [comment]
@DenielWorld please refrain from micromodding on the issue tracker. If you have nothing to help that contributes to the resolution of issues, please do not comment.

**Comment by SOF3** [comment]
This pull request alone does not contribute anything to PocketMine. Adding protocol constants without using them anywhere is pointless as these constants are not part of the API anyway.

**Pull request closed without merging**
