### PR TITLE
Fix issue with colored message on some languages

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
## Introduction

On some languages, there is a small issue on colored message.

Example:
In this example, italic is color.
If there's a message Testing _{%0}_ (English), it'll be shown as Bla _{%0} Hi_ (Some languages).

So this pull request fixes it.

### API changes

No

### Behavioural changes

No

## Backwards compatibility

Yes

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
What languages would this be an issue with? It can be reproduced easier if you tell us.

**Comment by Sandertv** [comment]
Yeah I get what he means, for example if you give a player an item with the /give command with a custom name, it would turn the rest of the message to that colour as well.

**Comment by Johnmacrocraft** [comment]
@TheDiamondYT1
Achievement: Korean, Arabic (Not sure), Dutch, German, Hungarian, Japanese, Turkish
Server startup: Korean, Chinese Traditional, Japanese, Turkish
@Sandertv Yeah, that's what I mean.

**Comment by Muqsit** [comment]
Why not TextFormat::RESET?

**Comment by Johnmacrocraft** [comment]
@Muqsit Changed it according to your suggestion.

**Comment by AppleDevelops** [comment]
@TheDiamondYT1 We like to change things to make other English speaking countries annoyed

**Pull request merged**
