### PR TITLE
DragonEgg and Elytra

### PR DESCRIPTION
**Pull request by ghost**
Add dragon egg to pocketmine

### CODE REVIEW

**Comment by Muqsit** [comment]
Oh god.. https://github.com/pmmp/PocketMine-MP/pull/931#issuecomment-302942076

**Comment by SuperMaXAleX** [comment]
Formatting *faceplam*
And there is already a rewrite of blocks and items, so this PR is useless.

**Comment by keithkfng** [comment]
@SuperMaXAleX "faceplam" *facepalm*

**Comment by dktapps** [comment]
This PR is a collection of copy-pasta from spoons and does not follow the contribution guidelines. Moreover, this system is being rewritten on a development branch.

**Comment by dktapps** [comment]
@keithkfng me too... I always mistype that :D

**Comment by SuperMaXAleX** [comment]
I need to calm down when I'm writing something
dOnT bE rUdE PlEaSe

**Comment by thebigsmileXD** [comment]
This is how to write facepalm: \*facepalm\*

**Pull request closed without merging**
