### PR TITLE
 DeviceOS: Add missing Linux constant

### PR DESCRIPTION
**Pull request by Blackjack200**
## Introduction
Add missing Linux constant
## Tests
**TESTED**

### CODE REVIEW

**Comment by Encritary** [comment]
what do you mean by Linux? there are at least two launchers (one being fork of another) that behave differently

**Comment by Blackjack200** [comment]
> what do you mean by Linux? there are at least two linux launchers (one being fork of another) that behave differently

sorry, i don`t know :(

**Comment by Blackjack200** [comment]
> what do you mean by Linux? there are at least two linux launchers (one being fork of another) that behave differently

my friend use ubuntu to play and DeviceOS is 20

**Comment by Encritary** [comment]
@Blackjack200 there's no official Minecraft Bedrock on Linux, so it doesn't make sense to add a constant here.

**Comment by dktapps** [comment]
how is it that **Saying "tested" or similar is not acceptable** in the PR template is so unclear?

**Pull request closed without merging**
