### PR TITLE
Added an easier function to quickly get an OfflinePlayer object from a Player object

### PR DESCRIPTION
**Pull request by Sandertv**
## Introduction

This pull request adds a very simple function: $player->getOfflinePlayer(). I felt like it would be easier to do this instead of having to construct a new OfflinePlayer object without API. 

### Relevant issues

No issues for this kind of addition.

### API changes

A new API function in the Player class:
`$player->getOfflinePlayer()`

### Behavioural changes

This does change the way anything behaves, nor performance.

## Backwards compatibility
 No backwards incompatible changes are made.

## Follow-up

-
## Tests

-

### CODE REVIEW

**Comment by dktapps** [comment]
why? I can't think of any circumstances where this would be needed.

**Comment by Sandertv** [comment]
This could make things easier with for example an API where an OfflinePlayer should be passed to the function instead of a Player object. If you have a Player object, it would be easier to use this function instead of having to construct a new object yourself.

I agree this isn't something which would be used very widely, but could come in handy in some occasions.

**Comment by dktapps** [comment]
again: why? why wouldn't you simply use the IPlayer interface?

**Comment by Sandertv** [comment]
Good point 😄

**Pull request closed without merging**
