### PR TITLE
fix(Entity): `broadcastSound()` not firing `WorldSoundEvent`

### PR DESCRIPTION
**Pull request by cooldogedev**
### Behavioural changes

`Entity::broadcastSound()` now fires `WorldSoundEvent`

### CODE REVIEW

**Comment by dktapps** [comment]
This should target `stable`

**Comment by ShockedPlot7560** [comment]
Was there any particular reason why it was implemented this way?

**Comment by dktapps** [comment]
Not that I can remember. Functionally, this changed version is the same.

That being said though, I wonder if we should have an `EntitySoundEvent` so that the source of the sound is obvious.

**Comment by ShockedPlot7560** [comment]
> That being said though, I wonder if we should have an `EntitySoundEvent` so that the source of the sound is obvious.

Question for another PR, it doesnt rely on this specific case which tend to just fix a bug. But the reflection is correct and would be taken into consideration for the future yes

**Comment by dktapps** [comment]
Yeah, you're right. I think this is good to merge by itself.

**Pull request merged**
