### PR TITLE
Add LiquidDecayEvent and BlockDecayEvent

### PR DESCRIPTION
**Pull request by AkmalFairuz**
## Introduction
Event when liquid decay like LeavesDecayEvent.
I have a Replay System, but the replay system doesn't record liquid when it decays

### API changes
- Added LeavesDecayEvent
- Added BlockDecayEvent
- LeavesDecayEvent is now `extends` to BlockDecayEvent class

### CODE REVIEW

**Comment by Matze997** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/src/block/Liquid.php#L342

Just use BlockSpreadEvent?

**Comment by AkmalFairuz** [comment]
> https://github.com/pmmp/PocketMine-MP/blob/stable/src/block/Liquid.php#L342
> 
> Just use BlockSpreadEvent?

BlockSpreadEvent not called when liquid decay

**Comment by dktapps** [comment]
This implementation will only be called when the final patch of liquid decays to nothing. It won't be called for the decay steps in between.

In addition, liquid disappearing and leaf decay are two entirely different mechanics, which are only related by poor choice of naming. They should not share an event.

**Comment by dktapps** [comment]
My previous comments on this topic were also never addressed: https://github.com/pmmp/PocketMine-MP/issues/4770

**Comment by jasonw4331** [comment]
The decay event itself is useful for block replacements without being cancellable

**Pull request closed without merging**
