### PR TITLE
Enable ANSI support for git bash

### PR DESCRIPTION
**Pull request by Frago9876543210**
## Introduction
Before:
default
After:
default

## Tests
Tested on git bash and Debian 9.

### CODE REVIEW

**Comment by dktapps** [comment]
this change is now pointless since you can simply write `start.sh --enable-ansi`.

**Comment by Frago9876543210** [comment]
I don't think it's convenient

**Comment by dktapps** [comment]
this is all missing the point... the fault here is that the colour support is not being correctly auto-detected. As I said, look at `Terminal::hasFormattingCodes()`.

**Comment by dktapps** [comment]
It appears that MSYS acts as a pipe, like lots of other console applications. Colour codes are automatically disabled when it's detected that stdout is a pipe.

**Comment by Frago9876543210** [comment]
Sometimes it is not piped
default

**Comment by SOF3** [comment]
Note: using the `winpty` command in Git Bash will also show colors.

**Comment by dktapps** [comment]
There isn't any cover all solution here that won't cause bugs. If this change is adopted, running `./start.sh > somewhere_else` will cause problems with character encoding when writing to a file (which is why it's disabled when a pipe is detected to begin with).

**Comment by lukeeey** [comment]
Add a startup option to force colours

**Comment by dktapps** [comment]
such a thing already exists 👏

**Comment by lukeeey** [comment]
Oh well I don't use this abomination

**Comment by SOF3** [comment]
Use an alias.

```bash
alias pm='./start.sh --enable-ansi`
```

**Pull request closed without merging**
