### PR TITLE
fix for projectile items like snowball

### PR DESCRIPTION
**Pull request by Eren5960**
## Introduction
Projectiles such as snowball could not be thrown in series

### Relevant issues
* Fixed  useHeldItem in Player.php

### API changes
no

### Behavioural changes
no

## Backwards compatibility
no

-->

## Tests
throw the snowball

### CODE REVIEW

**Comment by dktapps** [comment]
this fix is incorrect. If it was that simple, why do you think the change would not have already been applied?

this change breaks bows and any other item that has a release action.

**Comment by Eren5960** [comment]
You are right. I just realized this. I will try other ways

**Comment by Eren5960** [comment]
I tested with:
- Bow
- Shovel
- Snowball
- Ender Pearl

and working successfully

**Comment by dktapps** [comment]
this is still wrong. A bow is not a projectile, and projectiles don't have release actions. In addition, this breaks eating.

**Comment by dktapps** [comment]
never mind, i misread your code. Nonetheless, this flag should not be set if there isn't a release action and most items don't have that, hence the TODO.

**Comment by dktapps** [comment]
Fixed by #3664 .

**Pull request closed without merging**
