### PR TITLE
Position and Location function return now itself

### PR DESCRIPTION
**Pull request by DebHugo**
## Introduction
Allow function like `add`, `ceil`... in `Position` ans `Location` to return corresponding class instead of `Vector3`
This change allow to simplified code.

### Before:
```
$pos = new Position(1, 1, 1, $world);
$pos = Position::fromObject($pos->add(0.5, 0.5, 0.5), $pos->getWorld());
```
### After:
```
$pos = new Position(1, 1, 1, $world)->add(0.5, 0.5, 0.5);
```
$pos is now `Position` instead of `Vector3`

### API changes
Add function `add`, `multiply`, `divide`, `ceil`, `floor` in `Position` and `Location`

### CODE REVIEW

**Comment by DebHugo** [comment]
I'm not really fan of my modification. In my opinion there is a better way that doesn't require redeclaring all functions and is faster for Location. May be a function like this:
```
#In Vector3 class
protected function redifine(float|int $x, float|int $y, float|int $z): Vector3 {
	return new Vector3($x, $y, $z);
}

#In Position class
protected function redifine(float|int $x, float|int $y, float|int $z): Position {
	return new Position($x, $y, $z, $this->world);
}

#In Location class
protected function redifine(float|int $x, float|int $y, float|int $z): Location {
	return new Location($x, $y, $z, $this->world, $this->yaw, $this->pitch);
}
```
Function `redfine` would be call in `add`, `ceil`... functions and these function would be return `static` instead of `Vector3`
I wait your opinion.

**Comment by SOF3** [comment]
This is BC breaking because `$player->getLocation()->add(1,0,0)` now leaks the world.

Also it would become confusing which methods are overridden and which ones aren't. I think the root problem is that Position shouldn't have extended Vector3 to begin with.

**Comment by Nerahikada** [comment]
Related: #1367, #2989

**Comment by SOF3** [comment]
Also, it doesn't make sense for that `Position->add(Vector3)` returns Position but `Position->subtract(Vector3)` doesn't. Meanwhile, it makes even less sense that `Position->subtract(Position)` returns Position. So there is just no sane way to implement this in PHP.

[A white horse is not a horse](https://en.wikipedia.org/wiki/When_a_white_horse_is_not_a_horse), and a Position is not a Vector3. From what I understand, Vector3 is primarily a *relative* vector, which should not be usable as a position vector in any case.

**Comment by DebHugo** [comment]
> Also, it doesn't make sense for that `Position->add(Vector3)` returns Position but `Position->subtract(Vector3)` doesn't. 

I just forgot subtract

**Comment by DebHugo** [comment]
I just had an idea. Why not create a Position class that doesn't extend Vector3 and has a constructor like this
```
public function __construct(Vector3 $vector, World $world)
```

Consequently for have a vector use `Position->getVector()`
This manerie can fix issues with `Position` and `Location` class ?

**Comment by SOF3** [comment]
@Dhaiven this is what we've wanted to do all the time, except it would be yet another of the biggest BC breaks of all time

**Comment by dktapps** [comment]
Yeah, composing them would be the best technical solution, but would be shitty because of the amount of boilerplate code it would generate (look at the mess created from embedding Position in Block rather than extending it).

I've thought about doing this for Location specifically to split up the position and rotation parts, which would have a much smaller scope, but it would create problems for stuff like teleport().

> I just had an idea. Why not create a Position class that doesn't extend Vector3 and has a constructor like this
> 
> ```
> public function __construct(Vector3 $vector, World $world)
> ```
> 
> Consequently for have a vector use `Position->getVector()` This manerie can fix issues with `Position` and `Location` class ?

**Comment by SOF3** [comment]
In either case,
- It doesn't make sense that to perform `Position->multiply()`. The quantities in a position vector don't make sense unless you compare it to another position. In my opinion we should even *disallow* `Position->multiply()` if possible since that's almost definitely a bug.
- Same for `divide`.

**Comment by dktapps** [comment]
> In my opinion we should even disallow Position->multiply() if possible since that's almost definitely a bug.

I wouldn't go out of my way to do this. Without an architectural change this would violate LSP.

**Comment by dktapps** [comment]
> Meanwhile, it makes even less sense that Position->subtract(Position) returns Position.

Not sure what you meant by this, but the ambiguity in deciding which Position's World gets used is problematic indeed.

**Comment by SOF3** [comment]
> > Meanwhile, it makes even less sense that Position->subtract(Position) returns Position.
> 
> Not sure what you meant by this, but the ambiguity in deciding which Position's World gets used is problematic indeed.

The difference between two positions is a relative vector not a position. `(1010, 1010, 1010, world)` minus `(1001, 1001, 1001, world)` has absolutely nothing to do with the position `(9, 9, 9, world)`.

**Comment by dktapps** [comment]
Yeah, that's valid. I think this should be closed.

**Comment by SOF3** [comment]
If we actually have disjoint Vector3 and Position types, the following combinations involving Position would be valid:
```php
Position + Vector3 -> Position
Vector3 + Position -> Position
Position - Position -> Vector3
Position - Vector3 -> Position
```

all other operations, including all multiplication and division operations, would be unreasonable.

ceil and floor are fine, but they just don't look so nice in terms of BC when they leak the world.

**Pull request closed without merging**
