### PR TITLE
Remove unnecessary Cancellable implementation

### PR DESCRIPTION
**Pull request by zSALLAZAR**
## Introduction
Remove unnecessary Cancellable implementation

### CODE REVIEW

**Comment by zSALLAZAR** [comment]
Cancellable is already implemented in BaseBlockChangeEvent

**Comment by SOF3** [comment]
Does it really make sense to implement Cancellable on BaseBlockChangeEvent generically?

**Comment by dktapps** [comment]
I don't see why not, but it can't be changed before PM5 anyway.

**Comment by zSALLAZAR** [comment]
Why did you add the label "Waiting on Author"?

**Pull request merged**
