### PR TITLE
players spawn in the middle of the block

### PR DESCRIPTION
**Pull request by armagadon159753**
this pull request has been tested even after executing the following command: /setworldspawn

### CODE REVIEW

**Comment by jasonwynn10** [comment]
This isn't vanilla behavior

**Comment by legoboy0215** [comment]
I like the idea though.

**Comment by mal0ne-23** [comment]
Regardless of whether you like the idea or not, PMMP is made to simulate vanilla behavior. You can do anything you want with spawning using a plugin.

**Comment by armagadon159753** [comment]
OK i understand but un vanilla players spawn on Biddle if thé block and not beside

**Comment by TheDiamondYT1** [comment]
@armagadon159753 That comment contradicts your pull request...

**Comment by Sandertv** [comment]
Players actually do spawn in the middle of a block in vanilla, as @armagadon159753 mentioned, not on the corner of a block. (Tested on 1.2 Beta)

**Comment by TheDiamondYT1** [comment]
@Sandertv Oh, does this PR make players spawn in the middle of a block?

If so, this is a very confusing title. It sounds like the problem is spawning in the middle of the block and he is fixing it.

**Comment by Sandertv** [comment]
Block coordinates are always the corner of a block. As this is the case, adding 0.5 to both X and Z will spawn the player in the middle.

**Comment by armagadon159753** [comment]
@TheDiamondYT1 yes tested i working sorry for confuise

**Comment by dktapps** [comment]
This behaviour is correct, but I'm not sure about the implementation... thoughts anyone?

For example, teleporting to integer coordinates will place you at an offset of +0.5 in MCPC.

**Comment by armagadon159753** [comment]
@dktapps I have not yet tested the teleportation but I will keep

**Comment by dktapps** [comment]
This ought to be handled by the teleport mechanism (teleporting to block positions offsets the player by 0.5 blocks).

**Comment by armagadon159753** [comment]
thank you for paying attention ;) @dktapps

**Pull request closed without merging**
