### PR TITLE
Allow animated blocks with inventories to change their open/closed state arbitrarily

### PR DESCRIPTION
**Pull request by zSALLAZAR**
### Relevant issues

#2540

### API changes
Added `AnimatedBlockInventoryTrait->isClosed() : bool`
Added `AnimatedBlockInventoryTrait->open() : void`
Added `AnimatedBlockInventoryTrait->close() : void`

## Tests

https://user-images.githubusercontent.com/59490940/219906422-dab44cec-c281-4b6f-91b9-3990150798cb.mp4

### CODE REVIEW

**Comment by dktapps** [comment]
Relates to #2503

**Comment by dktapps** [comment]
Seems to me like this can be overridden quite easily by a player. A chest which is set in the "open" state with no viewers simply needs to be opened and closed by a player, and the chest's lid will close, despite having been set in the "open" state by a plugin.

**Comment by zSALLAZAR** [comment]
Adding an event for opening/closing animated blocks and canceling the event might solve this?
For example, if such event is canceled and a player opens and then closes a chest that is in the open state, the chest remains in the open state.

**Comment by dktapps** [comment]
What about this: `?bool $lockedOpenState = null`, where `null` means "default", `false` means "stays closed", and `true` means "stays open" (or possibly an enum for the same).

That being said, it's not so simple as this - you'd also need to address #2503 to have cosmetically open chests continue to display as open when new players come in range. (#2503 is currently a minor annoyance, but this feature would get the blame for it by users.)

I know you're probably not gonna reappear after 18 months and implement this, but I'll write it here for posterity.

**Comment by dktapps** [comment]
Closing due to lack of activity

**Pull request closed without merging**
