### PR TITLE
Added Dark Oak Tree 

### PR DESCRIPTION
**Pull request by Iam2smart**
## Introduction

Fixes Dark Oak Trees I hope

### CODE REVIEW

**Comment by Iam2smart** [comment]
I Do not know if this will work i am new so yeah code is bad but should work.

**Comment by dktapps** [comment]
have you ever seen a dark oak tree in game? Hint: it's not this simple...

**Comment by Iam2smart** [comment]
Yes I have seen what a Dark Oak Tree Looks like that why i said it was partial done

**Comment by lukeeey** [comment]
I don't get it how is it different other trees

**Pull request closed without merging**
