### PR TITLE
Fix enchantment typo

### PR DESCRIPTION
**Pull request by tarik02**
## Introduction

Enchantments file was copied from effects file, so somebody forgot to change one `Effect` to `Enchantment`

## Backwards compatibility

This is backwards incompatible(plugins was using Enchantment::getEffectByName needs to be updated)

### CODE REVIEW

**Comment by robske110** [comment]
good catch, looks like it has been copied from the effect class...

**Comment by Tarik02** [comment]
@robske110 yes, it is

**Comment by Tarik02** [comment]
I think will be better to split Enchantment item and Enchantment type like with items(ItemStack, Item)

**Comment by dktapps** [comment]
This issue has already been fixed on the api3/blocks branch.

**Pull request closed without merging**
