### PR TITLE
expose server instance for Entity class

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lukeeey** [comment]
why?

**Comment by DimBis** [comment]
> why?

why not?

**Comment by dktapps** [comment]
The burden of supporting an argument is on the person making the argument.

**Comment by dktapps** [comment]
I don't see any reasons to do this and I can think of a couple of reasons not to (forces Entity to have Server dependency, potentially breaks BC with custom entity classes), and so forth.

**Comment by SOF3** [comment]
Player provides getServer because it is required by CommandSender. I don't think it's appropriate to require getServer in CommandSender anyway, but removing it from CommandSender is another business. Meanwhile, adding it to more classes doesn't make sense.

**Pull request closed without merging**
