### PR TITLE
Add colors RBG to InstantEnchantParticle

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by YoungFad** [comment]
Changes: https://prnt.sc/rj3szg

**Comment by dktapps** [comment]
what exactly was the purpose of duplicating the PR?

**Comment by YoungFad** [comment]
I thought all of that commits would merge into one

**Comment by lukeeey** [comment]
It’s fine, when the PR is merged it can be made into a single commit using the “Squash and merge” button.

**Comment by dktapps** [comment]
I wondered why this looked familiar... #3118 

This feature has been added to the `next-minor` branch, so I'm closing this PR.

**Pull request closed without merging**
