### PR TITLE
Litle optimization

### PR DESCRIPTION
**Pull request by FaigerSYS**
It's better to create cache and compare it with packet buffer (faster)

### CODE REVIEW

**Comment by robske110** [comment]
why do you need an additional cache? the position is already saved?

**Comment by dktapps** [comment]
Only a microscopic amount faster in reality. I doubt such an optimization makes any noticeable difference.

**Comment by robske110** [comment]
Why ` < 0.01` actually? Isn't it just 0 if the player didn't move? or is there some value trimming/rounding somewhere.

**Comment by dktapps** [comment]
#259 floating-point errors when encoded in 4 bytes

**Comment by robske110** [comment]
It just looks so messy/hacky...

**Review by ghost — CHANGES_REQUESTED** [review]
I doubt how well this might improve performance. Any reliable statistics from a production server?

Also, would you confirm that the values will really be identical?

**Comment by dktapps** [comment]
As @poggit-orphanage said.

**Comment by Muqsit** [comment]
...andd Donald Knuth said.

**Comment by Dog2puppy** [comment]
Trump*

**Pull request closed without merging**
