### PR TITLE
Fix spawn protection bug (#3488)

### LINKED ISSUE #3488: spawn-protection placement bug
### Issue description

If you place a block one block outside of the spawn protection you can then place another block next to that one when the second block location is inside spawn protection. You are then unable to break the second block unless you are op. It doesn't always work the first time, but it does eventually let you place the second block.

Non-op should not be allowed to place blocks anywhere inside the spawn-protection area.

### Steps to reproduce the issue

- Find the edge of the spawn protection boundary.
- Place a block one past the boundary
- Place a block next to that one, inside the boundary.
- Profit!

https://imgur.com/DTI6dRZ

### OS and versions
PocketMine-MP 3.12.0 build #77d45bf
php v7.3.16
Linux XXXX  4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Plugins
No plugins.

### PR DESCRIPTION
**Pull request by kenygamer**
### Relevant issues

Fixes #3488 
## Changes
PocketMine spawn protection now takes into account placing blocks in edges of non-protected blocks
## Tests

Tested in my Ubuntu 16.04.6 LTS server

### CODE REVIEW

**Comment by CupidonSauce173** [comment]
Aren't you the scammer that also got banned in the forum?

**Comment by dktapps** [comment]
If he is, does that make the code change any less valid? Please refrain from making incendiary comments and keep it about the development, thank you.

**Comment by kenygamer** [comment]
@CupidonSauce173 Afternoon 👋
Are you going to keep rebuking me for something that happened 1-2 years ago? I have been commissioning plugins the last year perfectly fine and have had no issues ever since I started being punctual with delivery times and lowered my prices. Your commission was perhaps the second that I ever sold, and just because I inflated the price of that MySQL setup, are you going to keep blaming me? I delivered the project. I don't owe anyone anything, and yes, being banned has deprived me of clarifying this and rumors. It gave me lots of trouble. Also note I wasn't banned for scamming, I was banned for selling services. Ask the admins of the forum and please don't continue over something incorrect.

**Comment by dktapps** [comment]
Locking this before it turns into a battlefield. Take your arguments elsewhere, thank you.

**Pull request closed without merging**
