### PR TITLE
Added Item::getIdentifier

### PR DESCRIPTION
**Pull request by xxAROX**
### API changes
```diff
+ Item::getIdentifier()
```

### CODE REVIEW

**Comment by dktapps** [comment]
If you want to get a change merged, it should have some reason to be...

**Comment by xxAROX** [comment]
> If you want to get a change merged, it should have some reason to be...

No more `new ItemIdentifier` every time when getting the identifier from an Item

**Comment by dktapps** [comment]
That doesn't explain anything. I don't see why you need this at all.

**Comment by xxAROX** [comment]
For classes that uses ItemIdentifier as property for identifying an Item, if i construct such a class then i only do `$item->getIdentifier()` and no longer `new ItemIdentifier($id, $meta)`

**Comment by xxAROX** [comment]
if this makes no sense for you close the PR 👨

**Pull request closed without merging**
