### PR TITLE
Bump to 0.15.10

### PR DESCRIPTION
**Pull request by NoHaxJustTryHqrd**

### CODE REVIEW

**Comment by dktapps** [comment]
And did you actually test this properly, or just assume that because you were able to join that it was production-ready?
You make the same mistake everyone does. The protocol number is simply a version number. Modifying it does not cater for actual changes.
This pull request also does not comply with our contribution guidelines.

**Comment by robske110** [comment]
This protocol bump has to do sth with capes/skin handling. Not breaking the current code in any way, we do not (yet) read/write/send cape data.

**Comment by NoHaxJustTryHqrd** [comment]
This does not break any code in any way as 0.15.10 only added skins

**Comment by dktapps** [comment]
> This does not break any code in any way as 0.15.10 only added skins

that you know about. Protocol changes are not documented in the changelogs.

**Comment by SOF3** [comment]
@robske110 please prove it.

**Comment by NoHaxJustTryHqrd** [comment]
I will fully test this very soon when i do ill get back to you

**Comment by NoHaxJustTryHqrd** [comment]
Tested. Production ready. Up to you to merge

**Comment by SOF3** [comment]
We do not need you to tell us that 83 + 1 = 84.

The CONTRIBUTING.md will be updated soon to disallow this kind of pull requests.

**Pull request closed without merging**
