### PR TITLE
!spam

### PR DESCRIPTION
**Pull request by SashaManori**
scary plugin may do exceptional bad thing to pocket mine core. it important to protect and neutralize core from such attacks

### CODE REVIEW

**Comment by SashaManori** [comment]
update : fixes completion of server object construction ramification

**Comment by SalmonDE** [comment]
May I ask what exactly your changes protect against?

**Comment by SashaManori** [comment]
@SalmonDE you are just hater of protection ! shut up stupid noob ! this protect from scary plugin !

**Comment by SashaManori** [comment]
protects from start plugin call.

**Comment by SalmonDE** [comment]
I'm not hating at all. In fact I'm curious what bad thing a "scary plugin" could do.

**Comment by SashaManori** [comment]
mainly api harm

**Comment by dktapps** [comment]
bot left me in the lurch... thanks @SOF3

**Pull request closed without merging**
