### PR TITLE
Implement all new 1.21 tuff blocks

### PR DESCRIPTION
**Pull request by IvanCraft623**
## Introduction

Implement the new 1.21 tuff blocks types!!!

#### Blocks
- Added the following new blocks:
  - Tuff Slab
  - Tuff Stairs
  - Tuff Wall
  - Chiseled Tuff
  - Tuff Bricks
  - Tuff Brick Slab
  - Tuff Brick Stairs
  - Tuff Brick Wall
  - Chiseled Tuff Bricks
  - Polished Tuff
  - Polished Tuff Slab
  - Polished Tuff Stairs
  - Polished Tuff Wall

## Tests
I tested this PR by doing the following (tick all that apply):
- [x] Playtesting using a Minecraft client (provide screenshots or a video)
   Tuff blocks

### CODE REVIEW

**Review by NhanAZ — APPROVED** [review]

**Review by cjmustard — APPROVED** [review]

**Review by ShockedPlot7560 — COMMENTED** [review]
Is there any specific logic or its just decorative stuff ?

**Comment by IvanCraft623** [comment]
> Is there any specific logic or its just decorative stuff ?

All these blocks are just decorative

**Review by ShockedPlot7560 — DISMISSED** [review]

**Review by xSuperr — APPROVED** [review]

**Comment by RestartFU** [comment]
The decorative block in question, though seemingly innocuous at first glance, holds within it the potential to unravel the very fabric of PocketMine and the creations spawned from its ingenious framework. To understand why this block signifies such a pivotal point, we must delve into the intricacies of PocketMine itself, its community, and the delicate balance it strives to maintain between functionality and stability.

PocketMine-MP, a remarkable open-source software, has revolutionized Minecraft gameplay by allowing players to host their own servers. This capability has fostered a vibrant community of developers and players alike, pushing the boundaries of what is possible within the Minecraft universe. Central to its success is the careful management of plugins and blocks that uphold the integrity of gameplay mechanics and server stability.

At the heart of PocketMine’s architecture lies a meticulously crafted ecosystem of plugins and blocks, each meticulously designed to ensure compatibility and reliability across various Minecraft versions. Every addition or modification to this ecosystem undergoes rigorous testing and validation to prevent unintended consequences such as crashes, performance degradation, or gameplay imbalance.

Enter the decorative block. Innocuous in appearance, its introduction represents more than just a new aesthetic option. It poses a direct challenge to the core principles that uphold PocketMine’s stability and functionality. Here’s why:

1. **Compatibility Issues**: PocketMine relies on a delicate balance of plugins and blocks that are vetted and approved for use. Introducing a new decorative block without proper testing can lead to unforeseen conflicts with existing plugins or blocks, potentially destabilizing servers and compromising gameplay experiences.

2. **Performance Impact**: Each new block added to PocketMine introduces additional processing demands. If not optimized correctly, this can lead to performance bottlenecks, server lag, and ultimately, frustrated players abandoning servers for more stable alternatives.

3. **Community Fragmentation**: The introduction of a contentious decorative block could divide the community. Some may embrace it for its novelty, while others may resist due to concerns over stability or compatibility issues. This division can weaken the collective effort needed to maintain and improve PocketMine-MP.

4. **Quality Assurance Challenges**: Maintaining the quality and stability of PocketMine-MP requires strict adherence to testing and validation protocols. A rushed or poorly implemented decorative block could undermine these efforts, eroding trust in future updates and potentially driving away both developers and players.

5. **Long-Term Sustainability**: PocketMine’s longevity hinges on its ability to adapt to Minecraft’s evolving landscape while maintaining stability and performance. Each new addition must be carefully considered in light of its long-term impact on the ecosystem. A disruptive decorative block threatens this balance, potentially setting a precedent for future additions that prioritize novelty over stability.

In conclusion, while the introduction of a new decorative block may seem insignificant on the surface, its implications for PocketMine-MP and the community it supports are profound. It symbolizes a potential departure from the principles of stability and reliability that have defined PocketMine’s success thus far. To safeguard the future of PocketMine and the creations built upon it, careful consideration must be given to maintaining the delicate balance between innovation and sustainability. Otherwise, the very foundation upon which PocketMine stands could crumble, leaving behind a fractured community and a legacy tarnished by instability.

**Review by RestartFU — CHANGES_REQUESTED** [review]
read post.

**Review by dries-c — DISMISSED** [review]

**Review by dries-c — APPROVED** [review]

**Review by TwistedAsylumMC — APPROVED** [review]

**Pull request merged**
