### PR TITLE
InstantEnchantParticle: add Color into constructor

### PR DESCRIPTION
**Pull request by Frago9876543210**
## Introduction
These particles are similar to DustParticle and also have color

### CODE REVIEW

**Comment by Erkam246** [comment]
add nullable default 0

**Comment by dktapps** [comment]
could you provide some screenshots?

**Comment by Frago9876543210** [comment]
i

**Comment by Frago9876543210** [comment]
Initially, these particles were black, so it was suggested that they work by analogy with dust

**Comment by towuk118** [comment]
как на линухе майн запустил?)

**Comment by dktapps** [comment]
Those don't look like enchanting particles to me, more like coloured critical particles.

**Pull request merged**
