### PR TITLE
Kick the player who's tryna login with the username!

### PR DESCRIPTION
**Pull request by Assblocker**
## Introduction

This is necessary because if not, then the other logged in player gets kicked an he gets mad and starts complaining!
### API changes
No

### Behavioural changes
No

## Backwards compatibility
No

### CODE REVIEW

**Comment by KnownUnown** [comment]
This can be argued the other way as well. The currently logged in player may not be the real one, and the actual player who owns the username may be trying to join. The whole matter should be handled by authentication plugins anyway with PlayerPreLoginEvent.

**Comment by SOF3** [comment]
A better mechanism to tackle the issue can be implemented in a plugin, e.g. [checking IP](https://github.com/PEMapModder/HereAuth/blob/master/src/HereAuth/EventRouter.php#L89-L125)

**Comment by thebigsmileXD** [comment]
There are tons of plugins that do that, and this was a thing in pm once.. maybe it got removed.

**Comment by dktapps** [comment]
This matches to vanilla behaviour. If you want to alter that, use a plugin.

**Comment by dktapps** [comment]
also, who the hell is going to merge a PR from someone with a name like that... 🤦‍♂️

**Comment by Assblocker** [comment]
Tesseract did XD

**Pull request closed without merging**
