### PR TITLE
Throw exception when attempting to save a non-generated chunk

### PR DESCRIPTION
**Pull request by dktapps**
Should (hopefully) highlight what's going on with the big dirty holes in some generated maps.

### CODE REVIEW

**Comment by TheClimbing** [comment]
@dktapps Here is the [crashdump](http://pastebin.com/eLWSM33s)

**Comment by dktapps** [comment]
Awesome, that confirms it. 👍 thanks

**Comment by TheClimbing** [comment]
Should I test it now?

**Comment by dktapps** [comment]
Sure, feel free

**Pull request merged**
