### PR TITLE
Fix Fishing Rod

### PR DESCRIPTION
**Pull request by KennFatt**
- Set Fishing Rod as Tool
- Damageable (65 Durability)
- Set max count to 1 (as default tool)
- Fix "Unknown" to "Fishing Rod"

### CODE REVIEW

**Comment by corytortoise** [comment]
You should have done this from the api3/blocks branch, because a lot of item classes are being almost entirely rewritten there.

**Comment by KennFatt** [comment]
@corytortoise oh ok sorry, i'll move it. thanks for notice me! :gem:

**Comment by corytortoise** [comment]
You may want to look at the commits there for reference as to how dktapps wants tools added, assuming he isn't against anything being added to that branch right now.

**Comment by KennFatt** [comment]
@corytortoise ikr, if he ignore it, at least he read fishing rod is buggy and he will fix it with his way.

**Pull request closed without merging**
