### PR TITLE
Fixed crash on join game

### PR DESCRIPTION
**Pull request by Enes5519**
## Introduction
Fixed crash on join game

### API changes

**PlayerListEntry** remove third party and platform property and fields

### CODE REVIEW

**Comment by dktapps** [comment]
This code is wrong. Only 1.7 has these fields removed.

**Comment by Enes5519** [comment]
Hmm... I don't join game on 1.6 but I take crash but I do this. I join now

**Comment by dktapps** [comment]
Nobody else has reported issues, and this code is still wrong... you must be a special snowflake. ¯\_(ツ)_/¯

**Comment by Enes5519** [comment]
Wow. I'm amazed.

**Comment by dktapps** [comment]
I've asked someone else to independently check this. Here's the code: https://gist.github.com/MisteFr/368891d2d07d9f165f58499c225d549d

Thank you for wasting my time.

**Pull request closed without merging**
