### PR TITLE
Implement new pale oak blocks

### PR DESCRIPTION
**Pull request by ipad54**
This PR implements the new pale oak blocks.

## Changes
Added the following new blocks:
 - Pale Oak Button
 - Pale Oak Door
 - Pale Oak Fence
 - Pale Oak Fence Gate
 - Pale Oak Leaves
 - Pale Oak Log
 - Pale Oak Planks
 - Pale Oak Pressure Plate
 - Pale Oak Sign
 - Pale Oak Slab
 - Pale Oak Stairs
 - Pale Oak Trapdoor
 - Pale Oak Wood
 
### API changes
Added `WoodType::PALE_OAK`, `LeavesType::PALE_OAK`

## Tests
Screenshot_20241212_164808

### CODE REVIEW

**Comment by dktapps** [comment]
Code looks fine, I'm not familiar with these new blocks though.

Is there a sapling type for this? How are pale oak trees grown?

**Comment by ipad54** [comment]
Pale oak tree is a copy of dark oak tree with pale blocks.

I didn't include pale boat and sapling in the PR to not introduce unimplemented stuff.

**Comment by dktapps** [comment]
Makes sense. In that case I'm happy with this PR.

**Review by dktapps — APPROVED** [review]

**Comment by dktapps** [comment]
Welcome to merge this whenever you're ready. I'll leave it to you in case you want to tweak anything.

**Pull request merged**
