### PR TITLE
Add the parameter `int $step` to `Block::getAllSides()`

### PR DESCRIPTION
**Pull request by NhanAZ**
## Introduction
This parameter works as the `int $step` parameter of `Vector3::sides`

### CODE REVIEW

**Comment by dktapps** [comment]
I'm not really sure what the point of this is. Beyond a step of 1, you're just getting random blocks that just happen to be on the same axis as the block. There's no use case that I can see.

**Comment by SOF3** [comment]
What was the point of `$vector3->sides($steps)` to begin with?

**Comment by dktapps** [comment]
Good question. I think it came about during my attempt to separate Position from Block. The steps was a random thing I was able to add when this function was first introduced to begin with.

**Comment by SOF3** [comment]
@NhanAZ do you have any user stories for this? I don't see chances this is getting merged if there is no justification for such a confusing API.

**Comment by NhanAZ** [comment]
A simple use of this parameter: Create a cobblestone farm using water and fence
Here is the example code:
```php
	public function onBlockUpdate(BlockUpdateEvent $event): void {
		$block = $event->getBlock();
		if ($block instanceof Fence) {
			foreach ($block->getAllSides(2) as $key => $side) {
				if ($side instanceof Water) {
					$nearBlock = $block->getSide($key);
					if ($nearBlock->isSameType(VanillaBlocks::COBBLESTONE())) {
						continue;
					}
					$nearBlockPos = $nearBlock->getPosition();
					$nearBlockPos->getWorld()->setBlock($nearBlockPos, VanillaBlocks::COBBLESTONE(), false);
				}
			}
		}
	}
```
Cobblestone is generated when near the fence there is water.

**Comment by SOF3** [comment]
@NhanAZ what can't you flip the two if blocks and check the cobblestone first?

**Comment by dktapps** [comment]
This doesn't seem like a realistic use case.

What your code is doing is essentially this (in 2D):

```
..W..
.....
W.F.W
.....
..W..
```
The blocks closest to the fence are ignored.

Even if this was actually desired behaviour, it doesn't seem like a good enough use case to justify this change. You can simply do getSides() and then getSide(face) inside the loop to step out one block further (which your code actually does already to check for cobblestone).

**Comment by NhanAZ** [comment]
Thanks for taking the time to review this PR.

**Pull request closed without merging**
