### PR TITLE
spam

### PR DESCRIPTION
**Pull request by xDidntPot**
Comment to contribute!

### CODE REVIEW

**Comment by xDidntPot** [comment]
Fixes #4834 !

**Comment by xDidntPot** [comment]
ALL CHECKS PASSED BABY! MERGE MERGE MERGE!

**Comment by xDidntPot** [comment]
IT'LL HELP YOU IN DERIVIN' EM BITCHES!

**Comment by xDidntPot** [comment]
SOFE YOU DONT GOT BITCHES STAY MAD!

**Comment by xDidntPot** [comment]
LGBTQ IS A MENTAL ILLNESS STAY MAD FOLKS!

**Comment by thebigsmileXD** [comment]
You might be interested in https://github.com/thebigsmileXD/IsPregnant/

**Pull request closed without merging**
