### PR TITLE
Clear the title bar when the server shutdown.

### PR DESCRIPTION
**Pull request by OGFris**
## Introduction
It always annoys me how when i stop my server and want to keep my terminal open i still have the title of pocketmine.

### Relevant issues
Not a real issue.

## Changes
Now the title bar gets cleared when the server shutdown.

### API changes
No api changes.

### Behavioural changes
No behavioural changes.

## Backwards compatibility
No backwards compatibility.

## Follow-up
No action required after this pull request.

Requires translations:

| Name | Value in eng.ini |
| :--: | :---: |
| `foo.bar` | `Foo bar` |

--> No.

## Tests
This will clear the old pocketmine title bar text off the terminal (or cmd) when pocketmine shutdown just as simple as it sounds like.

### CODE REVIEW

**Comment by dktapps** [comment]
and what about when the user's console doesn't support ANSI escape codes? you just echoed some garbahe characters into their console...

**Comment by OGFris** [comment]
yea i guess but just do it, i hate it when the title still exists ugh

**Comment by dktapps** [comment]
I can't reproduce the bug you're talking about on any platform I've tested so far.

**Comment by OGFris** [comment]
well i have always got this bug on ubuntu but perhaps it's because of putty

**Comment by PotatoeTrainYT** [comment]
fris bad dev legacy sucks play sylph instead

**Comment by dktapps** [comment]
I tested native Windows, native Ubuntu, and Ubuntu in PuTTY, and have no sign of this bug. How odd.

**Comment by lukeeey** [comment]
i believe it happens on Android in termux when ssh'ing into a server

**Comment by dktapps** [comment]
That's more likely a bug in your terminal app than anything else.

**Comment by nnnlog** [comment]
@dktapps When I used XShell program, I could find this error.
```OS: Ubuntu 18.04, PM Version: lastest```

**Comment by dktapps** [comment]
I'm not merging this since you haven't addressed the issue of what happens when the user's console doesn't support ANSI escape codes. In that case, the console will likely misbehave or garbage characters will be shown on screen.

**Comment by OGFris** [comment]
alright i'll do it

**Comment by dktapps** [comment]
Merged with alterations as 69c54e789a13e426d411f1fd9e1273b75f9ac4f6.

**Pull request closed without merging**
