### PR TITLE
Fixed the awful debug > 1 confusion

### PR DESCRIPTION
**Pull request by ghost**
This may be controversial.

I always see users thinking there are more then one debug levels. This aims to fix confusions, and looks much nicer to me in my opinion.

### CODE REVIEW

**Review by dktapps — CHANGES_REQUESTED** [review]
I'm pretty sure \pocketmine\DEBUG is used elsewhere, it's scattered throughout the code.

I plan to implement proper debug levels in the future, so this serves no other purpose than reducing user confusion in the meantime.

**Comment by madcode15** [comment]
Alright.

**Comment by madcode15** [comment]
Ugh, Github client sucks, command line is much better especially when colaborating.

**Comment by dktapps** [comment]
yeah, don't use that... console ftw

**Pull request closed without merging**
