### PR TITLE
Bump v1.2.10

### PR DESCRIPTION
**Pull request by SuperKali**

### CODE REVIEW

**Comment by zKoz210** [comment]
Omg

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/mcpe/protocol/ProtocolInfo.php#L32-L36

**Comment by jojoe77777** [comment]
#1996

**Comment by SuperKali** [comment]
@jojoe77777 sorry, I had not seen

**Comment by dktapps** [comment]
unbelievable...

**Pull request closed without merging**
