### PR TITLE
MainLogger: Implemented log spam protection

### PR DESCRIPTION
**Pull request by dktapps**
## Introduction
This is designed to reduce log spam when a message is repeated identically consecutively in the log.

Currently this is a very basic mechanism. Spam is reported by the MainLogger when the next non-spam message is logged. It is also currently limited by timestamps (spam sent 1s apart will not be filtered).

This was inspired by Android's `chatty` log spam reducer.

### Behavioural changes
`MainLogger` will now minify spam messages. A message will be logged when the next message arrives to report how many log messages were skipped:
```
[11:16:47] [Server thread/INFO]: [test] Spam!
[11:16:48] [Server thread/INFO]: Previous message was repeated 9 times
```

## Test
Has been tested using a plugin and a repeating task to spam log messages.

### CODE REVIEW

**Comment by lukeeey** [comment]
You could just make a plugin which logs only useful stuff lol

**Comment by dktapps** [comment]
because of course, only plugins written by PMMP write spammy log messages... right?

**Comment by ByxNilsGFX** [comment]
Please create a New Generator for PMMP Worlds Implement Java World Format ty!

**Comment by SOF3** [comment]
@95CivicSi This pull request has nothing to do with reducing the size of server.log. It only aims to make it easier to read the console.

**Comment by 95CivicSi** [comment]
It may not be the aim of this PR @SOF3 but it is an effect of the spam reduction method employed. Whether intentional or byproduct, it is still useful.

**Comment by dktapps** [comment]
This is very limited and I don't have an interest in improving it, so I'm going to close it. PRs welcome if someone wants to implement a better version.

**Pull request closed without merging**
