### PR TITLE
Syntax PHP

### PR DESCRIPTION
**Pull request by SenseiTarzan**
PHP Standard

### CODE REVIEW

**Comment by SOF3** [comment]
I don't see how this pull request makes the intention of the code any clearer.

**Comment by SenseiTarzan** [comment]
it makes more sense than calling a variable twice for nothing

**Comment by SenseiTarzan** [comment]
@dktapps ???

**Comment by ghost** [comment]
It seems this PR is invalid.

**Comment by SenseiTarzan** [comment]
no there is just a problem with GitHub

**Comment by SenseiTarzan** [comment]
no there is just a problem with GitHub

**Pull request closed without merging**
