### PR TITLE
style(format): set method_argument_space

### PR DESCRIPTION
**Pull request by xerenahmed**

### CODE REVIEW

**Comment by SOF3** [comment]
nit: this isn't a `feat`, just a `chore`, right?

**Comment by xerenahmed** [comment]
You're right, but it's likely `style`

**Comment by dktapps** [comment]
Judging by the CI diff I don't think we're going to gain anything useful from this change. It's changing too many irrelevant things.

**Comment by SOF3** [comment]
This indentation doesn't look reasonable.
image

**Pull request closed without merging**
