### PR TITLE
feat(Server): add a setter for `maxPlayers`

### PR DESCRIPTION
**Pull request by cooldogedev**
## Introduction

This PR allows plugins to modify the server's max players count during runtime

### API changes

Added `Server::setMaxPlayers(int $maxPlayers): void`

## Tests

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [x] Playtesting using a Minecraft client (provide screenshots or a video)
- [x] Writing a test plugin (provide the code and sample output)
- [ ] Other (provide details)

### CODE REVIEW

**Comment by SOF3** [comment]
note that this is a BC break, e.g. for plugins that do a SplFixedArray($server->getMaxPlayers())

**Comment by dktapps** [comment]
does anyone do that?

**Comment by BrandPVP** [comment]
there is no bc break because there is no such plugins that call setMaxPlayers()

**Comment by Wraith0x10** [comment]
rip i was about to make a pr doing this too 🙏

**Review by dktapps — DISMISSED** [review]
I wonder if a `ServerPlayerLimitChangeEvent` is needed. Just wondering if some plugins might need to be informed of this change to invalidate caches or recompute stuff. Just a thought, not necessary to merge the PR.

**Pull request merged**
