### PR TITLE
Update core for PHP 7.1

### PR DESCRIPTION
**Pull request by dktapps**
## Introduction
read the title

### API changes
Alterations to `pocketmine\Thread->start()` and `pocketmine\Worker->start()` in accordance with pthreads 3.1.7-dev

### Behavioural changes
less performance because PHP 7.1 is somewhat slower than 7.0.

## Backwards compatibility
This is _not_ backwards-compatible with PHP 7.0, however most plugins won't be suffering breaking changes yet, at least until we start upgrading the core to use new features.

## Follow-up
- typehint all the things
- nullable typehints and void return types

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
If its slower, why use it?

**Comment by dktapps** [comment]
To demonstrate that it _is_ doable, we will need to upgrade at some point. This won't be merged for a while yet regardless, this version requires a dev build of pthreads (and pthreads itself has major issues at the moment).

**Comment by Muqsit** [comment]
Um, isn't pthreads an issue too?

**Comment by dktapps** [comment]
I'm going to have a play about with earlier versions... the big loss of performance started with php 7.1.2.

**Comment by dktapps** [comment]
This has been rebased on top of master and will now also work on php 7.2.0alpha1 with the correct binaries.

**Comment by AppleDevelops** [comment]
Is PHP 7.2 any faster?

**Comment by dktapps** [comment]
I don't know yet, all I know is that it works.

**Pull request closed without merging**
