### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by zSALLAZAR**

### CODE REVIEW

**Comment by JavierLeon9966** [comment]
This can target [next-minor](https://github.com/pmmp/PocketMine-MP/tree/next-minor) since this isn't a BC break.

**Comment by zSALLAZAR** [comment]
> This can target [next-minor](https://github.com/pmmp/PocketMine-MP/tree/next-minor) since this isn't a BC break.

How can I do that without adding all these commits?

**Comment by dktapps** [comment]
```
git rebase -i next-minor
```
delete everything except your commit
```
git push -f
```

**Comment by rasu3n** [comment]
`git rebase --onto=next-minor next-major`

**Comment by dktapps** [comment]
Cherry-picked onto `next-minor` as 7eca3e808120465a9dcd7390d0c936b91dcfde20. Thank you!

**Pull request closed without merging**
