### PR TITLE
RGB PMMP Logo

### PR DESCRIPTION
**Pull request by HBIDamian**
## Introduction
Updated PocketMine-MP Logo to the RGB variant.

### Relevant issues
N/A

### README:
Updated PocketMine-MP Logo to the RGB variant.

### CODE REVIEW

**Comment by HBIDamian** [comment]
## PocketMine-MP Logo (Dark Mode)
pocketmine-dark-rgb
## PocketMine-MP Logo (Light Mode)
pocketmine-rgb

**Review by dktapps — APPROVED** [review]
Perfect, thank you!

**Comment by arfush** [comment]
damn it's cool

**Comment by HBIDamian** [comment]
> damn it's cool
Project 2

**Pull request merged**
