### PR TITLE
Implement missing Nether Blocks [closed due conflicts and no help on discord ;(]

### PR DESCRIPTION
**Pull request by pandaaaBE**
This plugin adds follow things:
- Crimson Nylium/Fungus, Waped Nylium/Fungus, Nether Sporuts
- Huge Fungus (not perfect yet)
- Bone Meal Logic for Netherrack
- Adds support for Nylium to Mushrooms
- Adds support for Nylium to NetherRoots

### Add following Blocks
`VanillaBlocks::CRIMSON_NYLIUM(), VanillaBlocks::WARPED_NYLIUM(), VanillaBlocks::CRIMSON_FUNGUS(), VanillaBlocks::WARPED_FUNGUS(), VanillaBlocks::NETHER_SPROUTS()`

## TODO

- [ ] Ask someone for help, for the Huge Fungus
- [ ] Ask someone for help, for the Shears logic (Nether Sprouts)
- [x] Ingame Tests
- [x] Regenerate file for PHPUnit test, having issues to run the file

### CODE REVIEW

**Comment by pandaaaBE** [comment]
nvm i am using the code of object\TallGrass and block\Grass, should I use Position::getFloorX() or should I ignore the tests?

**Review by ShockedPlot7560 — COMMENTED** [review]
Missing Nylium support for mushrooms

**Comment by pandaaaBE** [comment]
> 2. Presently, certain blocks (fungus, nether grass, nether sprouts) are missing for the bone meal logic. Should I incorporate these blocks in a separate pull request, or is the current state acceptable?

@ShockedPlot7560

**Comment by ShockedPlot7560** [comment]
> nvm i am using the code of object\TallGrass and block\Grass, should I use Position::getFloorX() or should I ignore the tests?

You should ignore the errors if i remember. 

> Presently, certain blocks (fungus, nether grass, nether sprouts) are missing for the bone meal logic. Should I incorporate these blocks in a separate pull request, or is the current state acceptable?

The less that is done in a PR, the better it will be

**Comment by pandaaaBE** [comment]
> You should ignore the errors if i remember.

Ok thx :)

> The less that is done in a PR, the better it will be

:+1:

**Comment by pandaaaBE** [comment]
Oops, I merged something incorrectly. How can I undo this... lol

Also, the bone meal logic for the fungi is quite convoluted. Perhaps someone could take a look at the generator for me?

And one more thing: should I delete the Fungi abstract class and just override the Tree class?

**Comment by ShockedPlot7560** [comment]
There is some merge/diff noise which interferes with the review of PR.

**Comment by pandaaaBE** [comment]
https://minecraft.wiki/w/Nether_Sprouts

Is there something where I can add the drop logic for shears?

**Comment by pandaaaBE** [comment]
Small update:

It looks like there is no scissor logic, at least in the other blocks where there should be, I couldn't find it. -> If this is the case I will open an extra pull request next month.

Huge Fungus: didn't upload it before I changed Linux OS so it will take some time until I can do it again.

Both Nylium blocks cause strange "lags", e.g. you can't place blocks within a 2x2x2 radius or they bug out

**Comment by pandaaaBE** [comment]
Conflicting files
.github/workflows/main-php-matrix.yml
composer.json
composer.lock 

What can I do?

**Pull request closed without merging**
