### PR TITLE
change word

### PR DESCRIPTION
**Pull request by nnnlog**
## Introduction

change word

### CODE REVIEW

**Comment by jasonwynn10** [comment]
`The short data type is a 16-bit signed two's complement **integer**.` The wording should not be changed.

**Comment by robske110** [comment]
Actually ShortTag in the message is also wrong. He should change ShortTag->StringTag and int->string. Because this is in the StringTag class.

**Comment by jasonwynn10** [comment]
Right... I didn’t notice which file was being changed. I assumed it was ShortTag because of the message 🤔

**Comment by dktapps** [comment]
Copy pasta is so nice... would anyone like to PR and fix this properly?

**Comment by nnnlog** [comment]
@dktapps No **Copy Paste**

**Comment by SuperMaXAleX** [comment]
drink water

**Comment by dktapps** [comment]
https://media.giphy.com/media/jXD7kFLwudbBC/giphy.gif

**Comment by nnnlog** [comment]
@dktapps Live like that.

**Pull request closed without merging**
