### PR TITLE
Only reduce durability when armor reduced damage.

### PR DESCRIPTION
**Pull request by rasu3n**
## Introduction

Current behavior is different from vanilla.
(https://minecraft.fandom.com/wiki/Durability#Armor_durability)

### CODE REVIEW

**Comment by ghost** [comment]
Still, it's worth tweaking this decision a bit. Since poison, and some effects are also absorbed by armor, it is worth considering this too.

**Comment by dktapps** [comment]
> Still, it's worth tweaking this decision a bit. Since poison, and some effects are also absorbed by armor, it is worth considering this too.

Pretty sure that's not the case...

**Review by dktapps — APPROVED** [review]
Looks fine, but I think some investigation into the original code might be warranted (I doubt I missed this when I wrote the code to begin with).

**Comment by ghost** [comment]
> > Still, it's worth tweaking this decision a bit. Since poison, and some effects are also absorbed by armor, it is worth considering this too.
> 
> Pretty sure that's not the case...

Since it has not been tested, or rather I cannot test it, the author of the PR should do this. I myself am not very sure that after such changes, armor still takes damage from effects

**Comment by rasu3n** [comment]
> 

As dylan said their damage is not reduced by armor.

https://github.com/pmmp/PocketMine-MP/blob/0a9b52618d4ab570be914dc8083445714ca5df2b/src/event/entity/EntityDamageEvent.php#L160-L162
https://github.com/pmmp/PocketMine-MP/blob/0a9b52618d4ab570be914dc8083445714ca5df2b/src/entity/effect/PoisonEffect.php#L49
https://github.com/pmmp/PocketMine-MP/blob/0a9b52618d4ab570be914dc8083445714ca5df2b/src/entity/effect/WitherEffect.php#L40

**Comment by ghost** [comment]
Good

**Comment by rasu3n** [comment]
> Looks fine, but I think some investigation into the original code might be warranted (I doubt I missed this when I wrote the code to begin with).

It looks like it's been the same behavior since the armor durability was implemented.
https://github.com/pmmp/PocketMine-MP/commit/e06b78b0ee6b23c6cb91b5f4f73e6557a086b239

**Pull request merged**
