### PR TITLE
feat: support for MPE 1.21.30

### PR DESCRIPTION
**Pull request by andrebrito16**
## Introduction

Added support for Mineacraft v1.21.30

### API changes
Changed composer.json with versions.

## Tests

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [ ] Playtesting using a Minecraft client (provide screenshots or a video)
- [ ] Writing a test plugin (provide the code and sample output)
- [ ] Other (provide details)

### CODE REVIEW

**Review by dadodasyra — COMMENTED** [review]
Wrong indentation

**Comment by dadodasyra** [comment]
And protocol is not merge either so.. Doesn't make any sense at all

**Comment by WilliamThibo2** [comment]
hello, how to have pocketmine mp to the newest version?

**Comment by KaitoZerjoYT** [comment]
https://github.com/dries-c/PocketMine-MP/tree/bedrock-1.21.30

**Comment by KaitoZerjoYT** [comment]
> hello, how to have pocketmine mp to the newest version?

https://github.com/dries-c/PocketMine-MP/tree/bedrock-1.21.30

**Pull request closed without merging**
