### PR TITLE
Visibility keyword after final or abstract keyword.

### PR DESCRIPTION
**Pull request by Sandertv**
This pull request changes visibility keywords to be before the abstract and final keyword. This follows the PSR-2 standards, and should be discussed if somebody has objections. See https://github.com/Sandertv/PocketMine-MP/commit/b2eb0dfaa2f44fe012e80f094511b15b12651cfb

### CODE REVIEW

**Comment by dktapps** [comment]
As per the PSR-2 style guidelines [here](http://www.php-fig.org/psr/psr-2/):

> Visibility MUST be declared on all properties and methods; abstract and final MUST be declared before the visibility; static MUST be declared after the visibility.

This is therefore incorrect.

**Comment by TheDiamondYT1** [comment]
This just looks ***ing terrible imho

**Comment by Sandertv** [comment]
@TheDiamondYT1 
I prefer visibility before static/abstract/final too, but either of them is at least better than it is now. Now it's just a combination of both.

**Review by SOF3 — APPROVED** [review]
This correctly resolves all violations of PSR-2 regarding order of visibility and inheritance modifiers in this repo.

Note that in PocketMine-SPL, there is one violation of `final public` in ThreadedLoggerAttachment.php and two violations of `public static` in leveldb.php.

**Comment by kniffo80** [comment]
Coming from the JAVA world - this looks a little weird :expressionless:

**Comment by dktapps** [comment]
Nobody cares about the Java world. This is PHP.

**Comment by TheDiamondYT1** [comment]
Java 4 life

**Comment by SOF3** [comment]
This is not the place to show off what languages you know or what code styles you support.

Before someone starts a _jihad_ to DDoS servers not using Java, I'm locking this conversation. If you don't like this choice of code style, blame @shoghicp who chose PSR-2, or blame whoever drafted PSR-2 who decided this. We never require other developers to use the same code style, so if you did not even contribute any abstract or final functions to the PocketMine source code, this is entirely none of your business.

Please also note that neither the government of Java Island nor its supervising government of Indonesia has enacted the law that fines whoever places `abstract` before a `public` method.

**Pull request merged**
