### PR TITLE
Avoid useless loop into plugin description

### PR DESCRIPTION
**Pull request by matcracker**
## Introduction

The $plugin["authors"] already returns an array if is set, so it's useless iterate it.
### Relevant issues
Any issue. Just a micro optimization.

### API changes

No
### Behavioural changes

No
## Backwards compatibility

Yes

### CODE REVIEW

**Review by dktapps — CHANGES_REQUESTED** [review]
This will overwrite the `author` directive if both are used.

**Comment by matcracker** [comment]
> This will overwrite the `author` directive if both are used.

Wooops, I accidentaly deleted the brackets.

**Comment by dktapps** [comment]
The latest commit makes the problem worse. Now it's appending an array to an array.

**Review by lukeeey — COMMENTED** [review]
Shouldve probably used `array_merge`

**Comment by matcracker** [comment]
Yes, I did that but Dylan closed the PR before my commit. He's so cruel :(

**Pull request closed without merging**
