### PR TITLE
Add ender pearl

### PR DESCRIPTION
**Pull request by TheDiamondYT1**
This pull request adds the Enderpearl item, Enderpearl entity and the ability to shoot an enderpearl then teleport to that spot.

The amount of hearts you will lose is 3 and a half, like it vanilla. 
*(Yes, i know i put '3' in the code but it makes me lose 3.5 so yeah)*

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Hmm im guessing i will have to remove the age check (i copied the class from snowball entity) so i dont get teleported if the enderpearl is in the air too long?

**Comment by dktapps** [comment]
You are attempting to two of the worst parts of PocketMine-MP. One part has a rewrite already underway, the other is pending rewrite. This PR comes at a bad time.

**Comment by TheDiamondYT1** [comment]
@dktapps Oh, sorry. Should i close it?

**Comment by dktapps** [comment]
Thanks for your contribution, but yes, I think this should be closed.

Other readers take note: a PR being rejected doesn't mean we have anything against you, always pay attention to _why_ the PR is closed. It's not something to be afraid of.

**Comment by TheDiamondYT1** [comment]
@dktapps Just so i dont make another PR to it, whats the **other** worst part of pmmp?

**Comment by dktapps** [comment]
Entities are the worst part. Really awful stuff.

Blocks/items are also terrible, rewrite is currently under way on the api3/blocks branch. Entities are pending.

**Comment by madecode15** [comment]
@dktapps Yeah... entity ticking is a mess between classes... Also it is terribly optimized with performance.

**Comment by Thunder33345** [comment]
You should try to put notes so other contributors dont do the same thing

**Pull request closed without merging**
