### PR TITLE
A few changes to get rid of the extra loop

### PR DESCRIPTION
**Pull request by PechenkaPM**
## Introduction
I noticed a useless loop that iterates over all entities and can be removed

### Relevant issues
N/A

### API changes
N/A

### Behavioural changes
N/A

## Backwards compatibility
N/A

## Follow-up
N/A

-->

## Tests
Pending tests

### CODE REVIEW

**Comment by PechenkaPM** [comment]
I tested this, everything works

**Comment by dktapps** [comment]
We don't want to update every single entity every tick. In particular, inanimate / non-moving entities that are not within a ticking chunk won't get updated (e.g. stationary dropped items, paintings). This change will cause performance degradation.

**Comment by PechenkaPM** [comment]
You remove entities from the list of ticking (updateEntities), after which you call the "tickChunks" function, and it returns the entities back by calling "scheduleUpdate" for all "entities"

**Comment by dktapps** [comment]
Actually, it doesn't. As I said, it only updates entities which are within ticking chunks.

**Pull request closed without merging**
