### PR TITLE
Phar link is now working

### PR DESCRIPTION
**Pull request by Touficbatache**
I edited the README.md because Jenkins isn't working. The phar should be created automatically on every push... Just add this file to your repository so it works: https://gitlab.com/touficbatache/PocketMine-MP/raw/master/.gitlab-ci.yml.

### CODE REVIEW

**Comment by Touficbatache** [comment]
But why? I am doing everything and it works. I saw it on Genisys so why not here? It updates itself, it's not hard at all. Anyway, it's your choice...

**Comment by Sandertv** [comment]
Please refrain from mentioning Spoons/forks from PocketMine. PocketMine was not made to copy paste in.

**Comment by jasonwynn10** [comment]
In #321 @dktapps already stated that "We do not use GitLab because it's a pain in the butt to maintain synchronization, and GitLab is unreliable."

**Comment by Touficbatache** [comment]
@jasonwynn10 But I did everything for you, Gitlab updates the repo every 1
hour from this main one...

**Pull request closed without merging**
