### PR TITLE
Mcpe 1.2

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by NycuRO** [comment]
wow i get unblock?

thanks bro @dktapps 

and sorry for pr

**Comment by jasonwynn10** [comment]
PRs like this are the reason you were blocked...

**Comment by IrishPacks** [comment]
Why do you spam PRs on every repo you touch?

**Comment by dktapps** [comment]
also the spam-pings on every single thing you comment on...

**Pull request closed without merging**
