### PR TITLE
Fixed INT32_MIN

### PR DESCRIPTION
**Pull request by Enes5519**
## Tests
I tested on 32-bit :D

### CODE REVIEW

**Comment by Enes5519** [comment]
@dktapps When I test 32 bit, it returns as float not int.

**Comment by dktapps** [comment]
32-bit is not supported anymore...

**Comment by Enes5519** [comment]
@dktapps I know. I just wanted to prove it.

[image](https://hizliresim.com/lOYPyJ)

**Comment by dktapps** [comment]
What you wanted to prove is irrelevant.

> 32-bit is not supported anymore...

We are fully aware that 32-bit does odd things like this. That is one of the reasons I cut support for 32-bit.

**Comment by dktapps** [comment]
https://bugs.php.net/bug.php?id=53934

**Pull request closed without merging**
