### PR TITLE
Docusaurus

### PR DESCRIPTION
**Pull request by ghost**
## Introduction

As you probably can see [pmmp.io](https://pmmp.io) looks pretty bad and **does not provide any useful information**. My goal with this pull request is too make the homepage useful and make the documentation usable for beginners. I am doing this using an open-source project by [Facebook](https://github.com/facebook) called [facebook/docusaurus](https://github.com/facebook/Docusaurus).

### Relevant issues

I do not see any relevant issues, but I have seen some relevant conversations in Poggit and PocketMine-MPs Discord servers.
### API changes

No additions to the API.
### Behavioural changes

No change in how the server behaves.
## Backwards compatibility

No backwards incompatible changes.

## Development
All actual code is in `website/`. In order to work on this you must run `npm install` in `website/`, then `npm start`.

### Translations
Not at the moment, but it is planned.

## Tests

No tests are required due to the nature of the pull request.

### CODE REVIEW

**Comment by nathfreder** [comment]
At the moment you will only find the starting code. If you are looking for the documentation check out https://docusaurus.io/.

**Comment by dktapps** [comment]
This is in the wrong repository if you're targeting the website...

**Comment by nathfreder** [comment]
Docusaurus is setup to be in the project's repository, not a separate one.

**Comment by nathfreder** [comment]
I'll explain it later.

**Comment by nathfreder** [comment]
@dktapps Docusaurus is designed to be in the project's repository, not `*.github.io`, etc. The reasoning for that is the code for your website is in `website/` and the documentation is in `docs/` (the same level as `website/`), it would be strange to have a repository with only two folders.

**Comment by dktapps** [comment]
I'm closing this since it should target the website repo, not the source repository.

Also, I recommend don't make a PR until you have something remotely recognizable as a contribution. Right now this PR is full of generated gibberish and I would be wasting my time to review it because it is not ready.

**Comment by nathfreder** [comment]
Where would you like me to make a pull request when it is ready?

**Comment by dktapps** [comment]
On the website repository I would imagine.

**Comment by nathfreder** [comment]
Alright, thanks!

**Pull request closed without merging**
