### PR TITLE
First shot renaming Level -> World

### PR DESCRIPTION
**Pull request by dktapps**
This has been discussed for a while, but I decided to do it today because YOLO.

### CODE REVIEW

**Comment by dktapps** [comment]
Due to the problems created by chunkutils2, namespaces for classes presented by chunkutils2 are untouched by this PR. Those can be changed later on once we're happy with this.

**Comment by lukeeey** [comment]
We need some more of this YOLO attitude in PM :smile:

**Comment by dktapps** [comment]
This change is huge, so it had to take top priority before it develops millions of merge conflicts.

**Comment by TheShermanTanker** [comment]
> 
> 
> We need some more of this YOLO attitude in PM 😄

If only Cloudburst had the same attitude :/

**Pull request merged**
