### PR TITLE
Now the Right ItemIDs 

### PR DESCRIPTION
**Pull request by note3crafter**
## Introduction
Change item ids from music discs from https://minecraft.fandom.com/wiki/Music_Disc 
ItemID 504 505 506... is already for Copper Ingot and more newer items

### CODE REVIEW

**Comment by note3crafter** [comment]
I think is now the right ids! i cant find more about this id list!

**Comment by IvanCraft623** [comment]
These Ids are incorrect, the ones pocketmine has are right.

**Comment by note3crafter** [comment]
> These Ids are incorrect, the ones pocketmine has are right.

No its wrong 504 is Copper Ingot! 
Here https://minecraft.fandom.com/wiki/Copper_Ingot

Raw Iron is 505
https://minecraft.fandom.com/wiki/Raw_Iron

etc...

**Comment by IvanCraft623** [comment]
Your PR causes this:
https://cdn.discordapp.com/attachments/551141879123542020/1028419165729595392/SVID_20221008_161630_1.mp4

You are not solving anything, please test your PRs or at least make sure they work before sending them.

**Pull request closed without merging**
