### PR TITLE
Added missing drops for Bell

### PR DESCRIPTION
**Pull request by NTT1906**
## Introduction
Add missing drops for Bell
### Relevant issues
None

### API changes
None
### Behavioural changes
N/A
## Backwards compatibility
N/A
## Follow-up
N/A
## Tests
None

Attach scripts or actions to test this pull request, as well as the result
N/A

### CODE REVIEW

**Comment by jasonw4331** [comment]
Please ~~rebase onto next-minor instead of stable~~ merge into stable instead of next-minor

**Comment by dktapps** [comment]
This is a bug fix, it should target stable.

**Comment by dktapps** [comment]
This is actually pointless anyway, since blocks already drop themselves by default if the correct tool was used. This does nothing useful.

**Comment by NTT1906** [comment]
> This is actually pointless anyway, since blocks already drop themselves by default if the correct tool was used. This does nothing useful.

but what about being destroyed by nearby update?

**Comment by dktapps** [comment]
That's a general problem not specific to bells. This change causes an additional bug, which is that it drops when any tool is used (or none at all).

**Comment by NTT1906** [comment]
> That's a general problem not specific to bells. This change causes an additional bug, which is that it drops when any tool is used (or none at all).

Bell got dropped by any tools and none too.

**Comment by NTT1906** [comment]
https://user-images.githubusercontent.com/54394881/152657479-655694e6-8c17-4da7-a450-ad9ddc49de0f.mp4

**Comment by dktapps** [comment]
Even if that were true, overriding getDrops() is not the way to deal with it - that breaks a bunch of other things.

**Comment by NTT1906** [comment]
what is this whole weird-looking stuff...

**Review by jasonw4331 — APPROVED** [review]

**Review by ShockedPlot7560 — APPROVED** [review]

**Comment by ShockedPlot7560** [comment]
Can be merged I think

**Review by TobiasGrether — APPROVED** [review]

**Pull request merged**
