### PR TITLE
Adjust pretty name of closures on PHP 8.4

### PR DESCRIPTION
**Pull request by staabm**
## Introduction

related to https://github.com/php/php-src/pull/13550

see analog symfony change: https://github.com/symfony/symfony/pull/54614

## Tests

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [ ] Playtesting using a Minecraft client (provide screenshots or a video)
- [ ] Writing a test plugin (provide the code and sample output)
- [ ] Other (provide details)

### CODE REVIEW

**Comment by ShockedPlot7560** [comment]
PHP 8.4 is not officially supported

**Comment by staabm** [comment]
I was just crawling thru github for this particular php compat problem. 

Its not important for me to make this repo PHP 8.4 compatible

**Comment by dktapps** [comment]
I think this would be better filled by using [`ReflectionFunction::isAnonymous`](https://www.php.net/manual/en/reflectionfunction.isanonymous.php) in 8.2 and up

**Comment by staabm** [comment]
> I think this would be better filled by using [`ReflectionFunction::isAnonymous`](https://www.php.net/manual/en/reflectionfunction.isanonymous.php) in 8.2 and up

thats right, but it would require raising the [min-php version requirement](https://github.com/pmmp/PocketMine-MP/blob/08c6e63aac45a450fe3b437616ee8aa2500e04e2/composer.json#L8)

**Comment by dktapps** [comment]
Not if we gate it with a `PHP_VERSION_ID` check. This change makes me uneasy. This check was sketchy enough to begin with.

**Comment by dktapps** [comment]
I don't like this, but it's less work than trying to get PHPStan to not complain about any version-conditional logic I tried to implement...

**Pull request merged**
