### PR TITLE
Anti-cheat fixes, settings and API

### PR DESCRIPTION
**Pull request by dktapps**
- Added switches to allow disabling anti-noclip and anti-instabreak.
- Added API methods to allow plugin control of anti-instabreak and anti-noclip.
- Added PlayerIllegalMoveEvent, which is fired when a player attempts to clip through a block.
- Fixed anti-flight false-positives when falling (especially when server is heavily lagging)

There are still some minor issues with Toolbox flight-hacks not being detected under certain circumstances. However, many anti-flight-related issues have been fixed.

### CODE REVIEW

**Comment by robske110** [comment]
Finally a proper implementation

**Review by robske110 — APPROVED** [review]
Finally a proper implementation. I always wanted to see events and api for this.

**Comment by dktapps** [comment]
```
<?php

/**
 * @name CancelMoves
 * @main dktapps\CancelMoves
 * @api 3.0.0-ALPHA2
 * @description Cancels events to allow no-clip
 * @author dktapps
 * @version 1.0.0
 */

namespace dktapps{
	class CancelMoves extends \pocketmine\plugin\PluginBase implements \pocketmine\event\Listener{
		public function onEnable(){
			$this->getServer()->getPluginManager()->registerEvents($this, $this);
		}

		public function onIllegalMove(\pocketmine\event\player\cheat\PlayerIllegalMoveEvent $ev){
			$ev->setCancelled(false);
			$ev->getPlayer()->sendMessage(\pocketmine\utils\TextFormat::RED . "Stop hacking");
		}
	}
}
```
The script plugin I tested the events with (just for reference).

**Comment by dktapps** [comment]
Going to merge this now because I really need the irritation relief this provides. Get ready to bump your APIs again ppl.

**Pull request merged**
