### PR TITLE
Implemented composter

### PR DESCRIPTION
**Pull request by NTT1906**
## Introduction
Add composter. Is a copy of [4731](https://github.com/pmmp/PocketMine-MP/pull/4731) 

### Relevant issues
N/A

## Changes
- Add composter recipes and some minor changes to Crafting systems.

### API changes
- [CraftingManagerFromDataHelper::make()](https://github.com/pmmp/PocketMine-MP/blob/59de045ecbacfb9acc297e75170819727d68ae09/src/crafting/CraftingManagerFromDataHelper.php#L35)' first parameter is now an array.

## Backwards compatibility
No

## Follow-up
- Add a new "composts.json" file to [Bedrock Data](https://github.com/pmmp/BedrockData)

## Tests
None

Attach scripts or actions to test this pull request, as well as the result
Soon

### CODE REVIEW

**Comment by NTT1906** [comment]
umm, why it closed again?

**Comment by dktapps** [comment]
My intent was to reopen the original, but apparently you broke github in some weird way.

**Comment by NTT1906** [comment]
> My intent was to reopen the original, but apparently you broke github in some weird way.

 Uhm, so this pull request is dead again oof... What should I do now?

**Comment by dktapps** [comment]
Open a new one if you want. In the future don't just randomly close a PR because you think you made a mistake. Wait for someone to help you instead or you'll just make a bigger mess.

**Pull request closed without merging**
