### PR TITLE
Sami documentation generator

### PR DESCRIPTION
**Pull request by dktapps**
## Introduction
This is intended to eventually replace Doxygen as our source for generating API documentation, since Doxygen doesn't work very well with PHP and is not very pretty to look at.

### Why not phpDocumentor or other alternatives?
phpDocumentor is a very nice tool, but it requires additional extensions which are not packaged as part of our PHP builds, making it awkward for users to generate their own documentation. Sami is easy to use and easy to restyle & customize, and has a nice modern feel.

### CODE REVIEW

**Comment by Bruno99** [comment]
Can we already see the site for documentation with sami technology?

**Comment by nathfreder** [comment]
This is still a work in progress?

**Comment by dktapps** [comment]
I haven't worked on this recently because resources were diverted elsewhere.

**Comment by nathfreder** [comment]
What else does it require before merging?

**Comment by dktapps** [comment]
I don't recall off the top of my head. A pretty landing page was one of the things I was working on.

**Comment by nathfreder** [comment]
I may work on that, once the documentation site is complete. So that the themes match.

**Comment by nathfreder** [comment]
Fun fact: Sami is no longer maintained.

**Pull request closed without merging**
