### PR TITLE
default-unicode-for-json

### PR DESCRIPTION
**Pull request by nomirva**

### CODE REVIEW

**Comment by nomirva** [comment]
I think you need to make the default unicode option for json config. So that there are no problems with non-ascii alphabets.

**Comment by dktapps** [comment]
I don't see how this fixes anything. It changes the output representation, not the parsing.

**Comment by nomirva** [comment]
This is exactly what I propose. I didn't quite understand what you thought. I just want unicode characters not to be escaped. In the current state, you have to override the options for saving the json config yourself. In the same yaml, a similar option is already set.

**Comment by dktapps** [comment]
Considering that we're planning to get rid of Config (see #3766), I don't think it makes sense to change its behaviour this late in its life cycle. You can always add this option yourself if you want to alter the behaviour of your own JSON configs (or just stop using Config altogether).

**Pull request closed without merging**
