### PR TITLE
change API 3.0.0-ALPHA5 xD

### PR DESCRIPTION
**Pull request by StormCraftMCPE**

### CODE REVIEW

**Comment by Sandertv** [comment]
Really? Why?

**Comment by Driesboy** [comment]
wtf?

**Comment by IrishPacks** [comment]
Change your plugins to fit the API, not the API to fit your plugins.

**Comment by Misteboss** [comment]
*FACEPALM*

**Comment by SuperMaXAleX** [comment]
tfw

**Comment by ParkChanSol** [comment]
Change your plugin's api

**Comment by legoboy0215** [comment]
I'm surprised how this is still open lol

**Comment by dktapps** [comment]
@legoboy0215 people have to sleep sometime.

**Pull request closed without merging**
