### PR TITLE
Fix server MOTD showing on the wrong server in server list

### LINKED ISSUE #1208: MOTD still doing weird whenever it's custom
### Issue description

When I try to set a custom MOTD with
```
$this->getServer()->getNetwork()->setName("Server MOTD");
```
The Server would appear "offline" and shows the MOTD somewhere else

### Steps to reproduce the issue

1. Change the MOTD with a plugin

### OS and versions

* PocketMine-MP: 58214bb
* PHP: 7.0.20
* Server OS: Linux Debian
* Game version: PE/Win10 (delete as appropriate) Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

### PR DESCRIPTION
**Pull request by mal0ne-23**
## Introduction

The server MOTD will usually jump to another server in the list, and then update to the correct one after a bit.

### Relevant issues
Fixes #1208 

### API changes

None
### Behavioural changes

nope

## Tests

Tested and works.

### CODE REVIEW

**Comment by jasonwynn10** [comment]
Why does this solve the issue?

**Comment by mal0ne-23** [comment]
Because the previous "0" was supposed to be the server's ID. There are no methods currently in Raklib to get the server's ID though... Keeping it always 0 would send 0 to the list more than once (assuming most servers use pmmp), and then there would be duplicates and the client does dumb shit. Now it's always random, so each server has it's own ID on the list (unless there's a rare occasion of two of the IDs being duplicated)

**Comment by robske110** [comment]
@mal0ne-23 
>There are no methods currently in Raklib to get the server's ID though...
???
Are you talking about the server id? That can be get really easily in RakLibInterface.
Just replace the `"0"` with ?`(string) $this->server->getServerUniqueId()`.
That would nearly eradicate the possibility of a random collision.

**Comment by jasonwynn10** [comment]
@robske110 If it were supposed to be the Server Unique Id, then I think dk would have used that to begin with. I think that the `"0"` is actually the index of the server in the list of servers on the client

**Comment by xxFlare** [comment]
@robske110  The 1 in 9223372036854775807 chance of a random collision? 😛

Anyways, this PR isn't the correct solution:
image1

**Comment by mal0ne-23** [comment]
@xxFlare This has been tested and works on 1.2, idk about 1.1...

http://imgur.com/a/N7jhu

**Comment by robske110** [comment]
@xxFlare that is probably because the server is using this function perodically to update player cnt/other stuff and then it constantly sends new ids. That's why the server unique id should be used here probably

**Comment by jojoe77777** [comment]
@xxFlare mt_rand max value is 2147483647 (mt_getrandmax())

On-topic: as robske110 said, `$this->server->getServerUniqueId()`

**Comment by dktapps** [comment]
Sadly none of you are correct... this is indeed the simplest solution short of changing RakLib. This field is supposed to be the RakNet server ID, not a PM UUID.

**Comment by dktapps** [comment]
The correct server ID to use is [this one](https://github.com/pmmp/RakLib/blob/master/server/SessionManager.php#L84), however it's a little inaccessible. Since I was unable to reproduce this issue, I suggested this quick hack and it worked.

**Pull request closed without merging**
