### PR TITLE
Use PlayerAuthInputPacket::SNEAKING flag to test for sneaking

### LINKED ISSUE #5792: Sneaking while flying does not work
### Issue description

Sneaking with flight enabled does not work, which causes block interaction problems in creative mode.

### Steps to reproduce the issue
1. Place a chest
2. Fly
3. Press shift to sneak until you hit ground (or press space)
4. Click on the chest

Reproduced on test.pmmp.io:19132

### OS and versions

* PocketMine-MP: 5.0.0
* Game version: Windows

### LINKED ISSUE #5903: Being in the 1.5 block space is interpreted as pressing the shift key
### Issue description

- Expected result: The player interacts with the block
- Actual result: The player places a block

### Steps to reproduce the issue
1. Go into a 1.5 block high area
2. Don't press shift key
3. Hold a block in your hand
4. Try to click on a block that you can interact with

### OS and versions
* PocketMine-MP: 5.3.1
* Game version: Win10 (Not tested on others)

### Plugins
test.pmmp.io server's plugins

### Crashdump, backtrace or other files
https://youtu.be/cbSFCt28Phg

### PR DESCRIPTION
**Pull request by Muqsit**
`PlayerAuthInputPacket::SNEAKING` flag covers the case where a player is sneaking during flight, something which `START_SNEAKING` & `STOP_SNEAKING` currently do not.

### Related issues & PRs

* Fixes #5792 - sneaking during flight would cause ghost block to appear when placing block against a chest
* Fixes #5903 - players could not place blocks when within the 1.5 block space (i.e., under a slab)

### Behavioural changes

The server now correctly recognizes players who are sneaking while flying. Players are once again able to place blocks against interactable blocks (like chests and item frames) while in this state (without triggering block interaction). When under a slab (1.5 block space), players can place blocks and must explicitly sneak (on PC, by pressing shift key) to perform the usual sneak functionality.

## Tests

```php
// Debug chat message to test whether PlayerToggleSneakEvent is triggered as expected
// (i.e., no duplicate event calls, sneak event is initiated and terminated at proper times)
$plugin->getServer()->getPluginManager()->registerEvent(PlayerToggleSneakEvent::class, function(PlayerToggleSneakEvent $event) : void{
	$event->getPlayer()->sendMessage(gmdate("Y-m-d H:i:s.v") . ": sneaking=" . ($event->isSneaking() ? "yes" : "no"));
}, EventPriority::MONITOR, $plugin);
```
https://github.com/user-attachments/assets/dd4ec2fb-6785-4dbd-8f86-ad215943a406

https://github.com/user-attachments/assets/309a87ea-0503-44f2-b668-d7e70827fb28

### CODE REVIEW

**Comment by dktapps** [comment]
I'd imagine this probably fixes https://github.com/pmmp/PocketMine-MP/issues/5903 too.

I wouldn't be surprised if this kind of issue shows up with the other start/stop flags. Might be worth testing.

**Comment by Muqsit** [comment]
> I'd imagine this probably fixes #5903 too.
> 
> I wouldn't be surprised if this kind of issue shows up with the other start/stop flags. Might be worth testing.

After some discussion and testing, the issue above is also addressed by this fix. However this PR trades the sneak functionality for a visual bug where players appear standing while they are under a slab/the 1.5 block space.

**Comment by dktapps** [comment]
Per internal discussion, sneaking needs to be split into "interact" sneaking (disables block interaction) vs "actual" sneaking (makes the player appear to sneak, reduces its collision box) to fully address this.

**Comment by dktapps** [comment]
I think we can accept this for a patch release, but #6548 needs to be dealt with as soon as possible

**Review by dktapps — APPROVED** [review]

**Pull request merged**
