### PR TITLE
New bubbles colors

### PR DESCRIPTION
**Pull request by YoungFad**
## Introduction

Just a new feature
### API changes

No

### CODE REVIEW

**Comment by YoungFad** [comment]
Actually it's not water bubbles, it's just the potions bubble colors.

**Comment by dktapps** [comment]
this breaks backwards compatibility.

**Comment by lukeeey** [comment]
its still *technically* backwards incompatible as plugins made for the latest stable build won’t work on the older ones

**Comment by dktapps** [comment]
yes this is what we have minor versions for.

**Comment by dktapps** [comment]
I think it would be better if this used the Color class instead of a bunch of integers.

**Comment by dktapps** [comment]
now we are back to a backwards compatibility break.

**Comment by YoungFad** [comment]
No longer backwards compatibility break.

**Comment by dktapps** [comment]
I have no idea what you did in the last few commits but it's definitely not what I expected.

**Comment by YoungFad** [comment]
I'll close the PR and create new one to show the final result of it.

**Comment by dktapps** [comment]
I can see the final results of it just fine. You've made a mess in the last few commits.

**Pull request closed without merging**
