### PR TITLE
Fix GC Cycle Count Increases on Player Disconnect

### LINKED ISSUE #6484: Garbage Collection Cycle Count Increases on Player Disconnect
### Issue description

- Expected result: Running `/gc` in the console should show `Cycles: 0` after a player disconnects.
- Actual result: Running `/gc` shows `Cycles: 38` after a player disconnects.

This issue is caused by this code:
https://github.com/pmmp/PocketMine-MP/blob/b3b8aaddffe3b3a1eee8dcc62dd08fcd10581916/src/inventory/ArmorInventory.php#L45

### Steps to reproduce the issue
1. Join the game.
2. Quit the game.
3. Use `/gc` in the console to check the garbage collection cycle count.

### OS and versions

* PocketMine-MP: [5.21.0](https://github.com/pmmp/PocketMine-MP/releases/tag/5.21.0)

### Plugins
Plugins (0):

- If you remove all plugins, does the issue still occur? **Yes**

### PR DESCRIPTION
**Pull request by kostamax27**
# Introduction
As described in #6484, after a player disconnects, the cycle count increases.

### Relevant issues
Fixes #6484

## Tests

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [x] Playtesting using a Minecraft client (provide screenshots or a video)
- [ ] Writing a test plugin (provide the code and sample output)
- [ ] Other (provide details)

### CODE REVIEW

**Review by ShockedPlot7560 — COMMENTED** [review]
Transforming the validate into a static function could be better ?

**Comment by kostamax27** [comment]
> Transforming the validate into a static function could be better ?

What's the point of using the `ArmorInventory::validate` function? Are there any special reasons for this?

**Comment by dktapps** [comment]
It's nicer than baking it inline, but that's not the point. Don't change irrelevant stuff to achieve your objective.

**Review by dktapps — CHANGES_REQUESTED** [review]
Don't mix in unnecessary changes. A bug fix should contain the minimum necessary changes to solve the problem.

If you want to inline the function in a separate PR, you're welcome to do so, but since there's no obvious benefit to doing so it's unlikely to get merged.

**Review by dktapps — APPROVED** [review]

**Review by dries-c — APPROVED** [review]

**Review by ShockedPlot7560 — APPROVED** [review]

**Comment by ShockedPlot7560** [comment]
Thanks!

**Pull request merged**
