### PR TITLE
Added basic fire spread implementation

### PR DESCRIPTION
**Pull request by Sandertv**
…f login timeout.

## Introduction

This pull request adds basic fire spread implementation, both by lava and fire. This is NOT finished yet. I only made this pull request to get some feedback. 

### Relevant issues
No relevent issues, unimplemented feature.

### API changes

```
       /**
	 * Returns if the item is flammable
	 *
	 * @return bool
	 */
	public function isFlammable() : bool{
		return $this->flammable;
	}

	/**
	 * Returns if the item can catch fire if near lava
	 *
	 * @return bool
	 */
	public function canCatchFireFromLava() : bool{
		return $this->canCatchFireFromLava;
	}

	/**
	 * Returns the flammability of a block (the higher, the more quickly a block will burn away)
	 *
	 * @return int
	 */
	public function getFlammability(): int {
		return $this->flammability;
	}

	/**
	 * Returns the flame encouragement of a block (the higher, the more chance the block will catch fire)
	 *
	 * @return int
	 */
	public function getFlameEncouragement(): int {
		return $this->flameEncouragement;
	}
```

### Behavioural changes

Performance has not been tested. I have not been able to test this yet due to being timed out whenever trying to join the server using this branch.

## Backwards compatibility
 No backwards incompatible changes as far as I can tell. Mostly additions.

## Follow-up

Should be tested properly, and enhanced wherever possible. (Which is likely everywhere)

## Tests

None so far.

### CODE REVIEW

**Comment by Sandertv** [comment]
Yes, I am aware the formatting is messed up. I'll fix that next commit.

**Review by TheDiamondYT1 — COMMENTED** [review]
When blocks are moved to JSON (most likely by @dktapps) , this will be better there

**Comment by dktapps** [comment]
I am already working on jsonizing blocks, I just haven't decided exactly how I want to do it yet. The original purpose of this branch was to rewrite blocks, but I shifted to items because items were much simpler to jsonize. 

Items proved the concept is very effective if implemented correctly though, I can't even consider trying to add new stuff to the old system now I have a new system that works.

**Comment by Sandertv** [comment]
That's fine. I'll just remake it once that's done. For now some feedback would be nice though 😄

**Comment by dktapps** [comment]
My initial feedback is confine your changes to the topic of the PR only. Reformatting stuff and moving things around pollutes the diff and makes it more difficult to review changes.

**Comment by Sandertv** [comment]
Yeah... I noticed that too. I only intended to reformat the ones that I changed. My bad. I always manage to mess up pull requests.

**Comment by SalmonDE** [comment]
Wouldn't the FlameEncouragement need to consider the difficulty level?

**Comment by Sandertv** [comment]
Does flame encouragement change with difficulty? I know it should be able to disable it through gamerule or something though.

**Comment by dktapps** [comment]
As per the wiki:

> actual flammability and burn time depends not only on these values, but on difficulty, rain, the age of the fire, and a certain amount of randomness due to block ticks, among other things.

**Comment by SalmonDE** [comment]
@dktapps I've just read that, came back here and saw this. ;-;

**Comment by SalmonDE** [comment]
I think I phrased my comment a bit wrong, I wanted to ask if it's not necessary to consider difficulty in general, not just in the encouragement. Is this already in this pr? I couldn't find it.

**Comment by Sandertv** [comment]
I'll probably be better off waiting for one of the weather PRs to get merged as well so this can be implemented properly.

**Comment by TheDiamondYT1** [comment]
For reference https://github.com/Bukkit/mc-dev/blob/c1627dc9cc7505581993eb0fa15597cb36e94244/net/minecraft/server/BlockFire.java

**Comment by Sandertv** [comment]
Shuushhhh @TheDiamondYT1 we're not java ._.

**Comment by TheDiamondYT1** [comment]
@Sandertv Read the code. It mentions the `doFireTick` game rule and world difficulty

**Comment by TheDiamondYT1** [comment]
It could be useful for reference

**Comment by Sandertv** [comment]
Yeah I know, the gamerule was what I mentioned above as well. The wiki doesn't say anything about the difficulty though.

**Comment by TheDiamondYT1** [comment]
@Sandertv ...that is why I linked the file. I have a more up to date version of the fire block if you would prefer

**Comment by Sandertv** [comment]
Don't worry, I'll be working on it later anyways. I'm fine ^^ Thanks anyways. Let's not spam people anymore now! 😄

**Comment by HimbeersaftLP** [comment]
"and a certain amount of randomness" LOL

**Comment by TheDiamondYT1** [comment]
https://gist.github.com/TheDiamondYT1/e998a5cc7413e7ac315f5f73e9459783

@HimbeersaftLP

**Pull request closed without merging**
