### PR TITLE
Added Entity::getLastLocation,Entity::getLastMotion

### PR DESCRIPTION
**Pull request by xxAROX**
## Introduction
Cannot get `lastLocation`,`lastMotion` from outside of entity class.

### API changes
```diff
+ Entity::getLastLocation()
+ Entity::getLastMotion()
```

*i don't know why its not already built in*

### CODE REVIEW

**Comment by dktapps** [comment]
> i don't know why its not already built in

what would you need it for? it's only used internally for deciding whether to send movement packets over the network...

**Comment by xxAROX** [comment]
detect if a entity moved: x, y, z, yaw and pitch

**Comment by xxAROX** [comment]
*i need it for all kind of entities*

**Comment by dktapps** [comment]
Adding an API because you need it for something specific never ends well. This code won't make it to a release for weeks at best, even if it's merged.

**Comment by xxAROX** [comment]
currently i use reflection property to get the value, but thats annoying it would be easier with the changes

**Comment by xxAROX** [comment]
> Adding an API because you need it for something specific never ends well. This code won't make it to a release for weeks at best, even if it's merged.

then i change it when the update comes 🤷‍♂️

**Comment by dktapps** [comment]
I don't think it makes much sense to expose these. As I said previously, this is only used internally for deciding whether to send network packets or not. It's only updated when those packets are sent. Given that the conditions for sending packets don't necessarily align with the expectations of plugins, I'm doubtful that exposing these is sensible.

**Comment by xxAROX** [comment]
okay

**Pull request closed without merging**
