### PR TITLE
Remove useless statement

### PR DESCRIPTION
**Pull request by iPocket**

### CODE REVIEW

**Review by SOF3 — APPROVED** [review]
Really, this almost doesn't affect performance at all, but I'm fine with this change.

**Comment by legoboy0215** [comment]
I wanted to do that too, but doesn't this seem too minuscule? Anyways, that extension seems to be for Unit testing anyways.

**Review by SOF3 — DISMISSED** [review]
The extension being totally unused in the core, the only difference would be to completely delete these lines or not. Whether commenting out one or two more lines does not affect anything at all.

**Comment by legoboy0215** [comment]
What about the Pocketmine native extension? I never heard of anyone using it lol

**Comment by SOF3** [comment]
@legoboy0215 it is probably an extension written for pre-1.4.1 versions.

**Review by dktapps — APPROVED** [review]

**Review by SOF3 — APPROVED** [review]

**Pull request merged**
