### PR TITLE
Call BlockTeleportEvent when dragon egg teleports

### PR DESCRIPTION
**Pull request by Frago9876543210**
## Introduction
Now when the dragon egg tries to teleport it is calls BlockTeleportEvent

### CODE REVIEW

**Comment by dktapps** [comment]
This is an abuse of BlockUpdateEvent and not what it's designed for.

**Comment by Frago9876543210** [comment]
What event do you suggest?

**Comment by HimbeersaftLP** [comment]
DragonEggTeleportEvent obviously

**Comment by Frago9876543210** [comment]
One event per feature? Okey, will commit tomorrow

**Comment by dktapps** [comment]
The logic is specialized to this specific block. Go with `BlockTeleportEvent` if you're bothered. This logic will be separated into a component in the future.

**Pull request merged**
