### PR TITLE
Add new BiomeIDs

### PR DESCRIPTION
**Pull request by pandaaaBE**
Source: https://minecraft.wiki/w/Biome/ID

### CODE REVIEW

**Comment by dktapps** [comment]
As far as I remember, this file is generated from here: https://github.com/pmmp/BedrockData/blob/master/biome_id_map.json

**Comment by pandaaaBE** [comment]
Okay, then this PR is irrelevant, just see it as an issue it will probably be faster if you do it when you have time or someone wants to teach me something new and tells me where to find the file to generate :)

**Comment by ShockedPlot7560** [comment]
It seems that this file is generated yes. However, there are no tools or documentation to generate it. @dktapps do you have the link to this tool or does this file need to be edited manually now?

**Comment by dktapps** [comment]
It's probably lurking in my local workspace somewhere, I'll dig it up later

**Comment by dktapps** [comment]
Fixed by 61d0181bfd7122d76109f8ff390675eaf35f3da3 and 2616d8c5adacff29de6a8db17c8e13a075ff5ea9.

**Pull request closed without merging**
