### PR TITLE
Implement Command Parameters

### PR DESCRIPTION
**Pull request by Enes5519**
**NOT FINISHED**
## Introduction
Implemented parameters for commands

### Relevant issues
* Fixes list commands

### API changes
**Functions**:
Command::getData()
Command::addParameter()
Command::setParameter()
Command::setParameters()
Command::removeParameter()
Command::removeAllParameters()
Command::removeOverload()
Command::getOverload()
Command::getOverloads()
Command::setOverloads()

* Added constructor to some files

## Tests
pmmp_commands

### CODE REVIEW

**Comment by dktapps** [comment]
please, no spoon copy pasta... this code is planned for rewrite in the near future anyway.

**Comment by Enes5519** [comment]
This is no copy pasta. This is my code and reimprove on pmmp

**Comment by Enes5519** [comment]
Spoon you're talking about belongs to me.

**Comment by dktapps** [comment]
I'm fully aware of this. It doesn't make it any more acceptable. Please read the contribution guidelines before creating any more pull requests.

As I said above, this code is due for rewrite anyway. By itself, this command parameters implementation is next to useless, so I don't see the point of merging it regardless.

**Pull request closed without merging**
