### PR TITLE
start.sh: Skipping the script arguments

### PR DESCRIPTION
**Pull request by ghost**
## Introduction
Now the `start.sh` can be used as a runner for any PHP crap! Well, there will still be no extra parameters to the PocketMine-MP

### CODE REVIEW

**Comment by dktapps** [comment]
I don't see the point.

**Comment by ghost** [comment]
`./start.sh composer.phar update` instead `./bin/php7/bin/php composer.phar update` (or extra symbolic link like `ln -s ./bin/php7/bin/php php`).

Also, plugins can use the arguments passed. For example: https://github.com/poggit/devirion, use CLI arguments

**Comment by ghost** [comment]
This change is just for convenience. And I doubt it will ruin anyone's life

**Comment by dktapps** [comment]
If you want a change for your own convenience, you can easily create your own script.

Besides, it's simpler to just prefix the PHP binary path to your PATH environment variable instead of overengineering a script that wasn't intended for this purpose anyway.

**Pull request closed without merging**
