### PR TITLE
Add Vector2::setComponents, Vector2::getComponents, Vector3::getComponents

### PR DESCRIPTION
**Pull request by Tarik02**
## Introduction

Vector3 contains method setComponents, so lets add the same to Vector2.
Also like they have setComponents, so lets add getComponents

### API changes

- Added Vector2::setComponents
- Added Vector2::getComponents
- Added Vector3::getComponents

## Backwards compatibility

Backwards compatible

### CODE REVIEW

**Comment by dktapps** [comment]
what is the use case for getComponents()?

**Comment by Tarik02** [comment]
@dktapps
```php
list($x, $y, $z) = $sign->getComponents();
```
is really looks better than
```php
$x = $sign->getX();
$y = $sign->getY();
$z = $sign->getZ();
```

**Comment by Tarik02** [comment]
@SOF3 so what do you want to change in this PR?

**Comment by SOF3** [comment]
@Tarik02 I don't think addition of `getComponents()` is reasonable.

**Comment by jasonwynn10** [comment]
whatabout setComponents() ?

**Pull request closed without merging**
