### PR TITLE
Don't use stdClass for nbt, add temporary magic methods.

### PR DESCRIPTION
**Pull request by tarik02**
It's a little optimization of CompoundTag class, that has performance leaks with stdClass's.

### CODE REVIEW

**Comment by Tarik02** [comment]
This is not full solution of the issue, but it can speed up CompoundTags.
https://github.com/pmmp/PocketMine-MP/issues/466

**Comment by dktapps** [comment]
I don't think micro optimization is going to help the situation, the NBT library needs a full rewrite. Regardless, I'd like to see some tests that show some evidence that this provides an enhancement.

**Comment by Tarik02** [comment]
Yes, this don't helps fully, but this can be temponary solution of problem.

**Comment by Muqsit** [comment]
Nice, but whats the need of a temporary solution when it's eventually going to be removed soon?

**Comment by kniffo80** [comment]
@Muqsit removed soon? Where did you get that from?

**Comment by Tarik02** [comment]
@kniffo80, nbt in pocketmine will be rewritten from scratch soon, so this improvement will be removed.

**Comment by madecode15** [comment]
I tested this. There are no noticeable performance improvements, seems to be a micro-optimization. For issue #466 dktapps is talking about fixing the slow 22ms it takes to process NBT data. This is in no way a temporary solution...

**Comment by SOF3** [comment]
I believe @shoghicp had evidence that his approach is better than using __get when he initially wrote this library.

**Comment by Tarik02** [comment]
@SOF3, yes, but stdClass is not so fast thing.

**Comment by dktapps** [comment]
Everything in PHP is slow. Playing on the micro optimizations isn't going to help anybody.

**Comment by Muqsit** [comment]
Make another C extension for handling NBTs 😂

**Comment by dktapps** [comment]
Note that C-ifying everything won't make it magically faster. The ChunkUtils extension produced a huge performance improvement to Anvil worlds because it cut out thousands of PHP method calls (ord(), chr()) by dealing with bytes on a C level (method calls are very expensive). The same won't apply so much to NBT.

**Comment by Tarik02** [comment]
I think, that nbt is so slow because of many instanceof operators.

**Comment by madecode15** [comment]
@Tarik02 

No, instanceof call are not "slow". They are not the fastest operation either but that has nothing to do with anything.

After reviewing the code I think it is best to leave this untouched. According to php.net:
> Caution
PHP reserves all function names starting with __ as magical. It is recommended that you do not use function names with __ in PHP unless you want some documented magic functionality.

You can micro-optimize something hundreds of times and you won't save a single ms.

Best to wait for a actual solution by dktapps.

**Comment by madecode15** [comment]
@dktapps Is the ChunkUtils extension public now?

**Comment by dktapps** [comment]
https://github.com/dktapps/PocketMine-C-ChunkUtils

**Comment by madecode15** [comment]
I don't have much time to benchmark it right now, but is it faster then the MCRegion world provider? If I remember correctly PocketMine process Anvil the slowest (which chunk utils speed up).

**Comment by dktapps** [comment]
Any results you may remember from before 1.0 are now invalidated. The chunk format changed in 1.0 to accommodate the 256 build height.

McRegion used to be the fastest of the bunch due to its save format matching the MCPE network format. That's no longer true, which results in McRegion having a significant slowdown due to conversion. We also don't recommend using McRegion anymore since it doesn't support to 256-block build height.

Anvil without the C extension is extremely slow though, yes. The new chunk format is similar to Anvil, but with data order XZY instead of YZX. The PHP conversions of those chunks take a large amount of time, hence the performance issues. The C extension alleviates those.

**Pull request closed without merging**
