### PR TITLE
the plugin config folder is no longer created

### PR DESCRIPTION
**Pull request by forsterik**
Removed annoying empty folders that are created when the plugin is launched, but the plugin does not use this folder

### CODE REVIEW

**Comment by SOF3** [comment]
See discussion in https://github.com/pmmp/PocketMine-MP/pull/2284

**Comment by dktapps** [comment]
Hi, this behaviour is intentional. It was introduced in 3.2.0 because it became apparent that it was easier to have some empty directories instead of having to have every single plugin duplicate the same three lines at the top of their `onEnable()` routine. Reversing this now would have backwards-compatibility ramifications. See #2284 for further insights on this.

**Comment by SOF3** [comment]
In particular, could you describe how "annoying" it is? The plugin_data folder should contain as many folders as number of files in your plugins folder. How is that actually annoying?

**Comment by dktapps** [comment]
I don't think there's any point rehashing this since it was already discussed in #2284. Unless there's new material to be brought to the table, I think it would be better to let #2284 speak for itself.

**Comment by forsterik** [comment]
I apologize for my inattention, thank you all!

**Pull request closed without merging**
