### PR TITLE
Fixed anvil placing rotation.

### PR DESCRIPTION
**Pull request by ipad54**
## Introduction
The rotation of anvil was changed a few versions ago.

## Tests
I tested this PR by doing the following
- [X] Playtesting using a Minecraft client (https://www.youtube.com/watch?v=MNSudW6vbcQ)

### CODE REVIEW

**Review by nicholass003 — APPROVED** [review]

**Comment by IvanCraft623** [comment]
Pretty sure this change is a bug fault of their migration from old `direction` to `minecraft:cardinal_direction` block state

**Comment by IvanCraft623** [comment]
Reported: https://bugs.mojang.com/browse/MCPE-183397

**Comment by ShockedPlot7560** [comment]
Is this a client bug so ? I don't really understand what side is the fault.

**Comment by ipad54** [comment]
> Reported: https://bugs.mojang.com/browse/MCPE-183397

Mojang has closed your report as `Won’t fix`, so I think they are not going to fix this inconsistency in the near future…

**Review by IvanCraft623 — APPROVED** [review]
In view of the fact that mojang does not plan to fix it....

**Review by dktapps — APPROVED** [review]

**Pull request merged**
