### PR TITLE
Add Player parameter in BlockGrowEvent

### PR DESCRIPTION
**Pull request by DebHugo**
## Introduction

#5595 

### API changes

Added an optional that accept Player or null, default is null and add a function getPlayer()

### CODE REVIEW

**Comment by dktapps** [comment]
BlockGrowEvent is called in many more places, not just crops.

The build also needs to pass.

**Comment by DebHugo** [comment]
I don't understand why there is an error in the code style check.
I'll let you fix it yourself.

**Comment by dktapps** [comment]
It's because there's trailing whitespace on those lines. You can download and run [php-cs-fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases) to fix the issues automatically.

**Comment by DebHugo** [comment]
I finished. It is good for you ?

**Review by dktapps — APPROVED** [review]

**Pull request merged**
