### PR TITLE
Update ProtocolInfo.php

### PR DESCRIPTION
**Pull request by MCNationPE**

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Github should provide a way for repo admins to disallow making PRs for certain files to help prevent useless PRs such as this

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/mcpe/protocol/ProtocolInfo.php#L19

**Comment by TheDiamondYT1** [comment]
@dktapps Maybe that needs to be in caps with some asterics above and below it.
```
***************************************************************
 THIS FILE IS GENERATED AUTOMATICALLY, DO NOT EDIT IT MANUALLY
***************************************************************
```

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/mcpe/protocol/ProtocolInfo.php#L42

emphasis on _earliest supported version_

**Pull request closed without merging**
