### PR TITLE
Added missing Window Types

### PR DESCRIPTION
**Pull request by TwistedAsylumMC**
## Introduction

PocketMine has been missing a few window types, but this pull request adds their IDs to the WindowTypes class.

### API changes

- The constant ``WindowTypes::LOOM`` has been added with the value 24
- The constant ``WindowTypes::LECTERN`` has been added with the value 25
- The constant ``WindowTypes::GRINDSTONE`` has been added with the value 26
- The constant ``WindowTypes::CARTOGRAPHY`` has been added with the value 30

### Behavioural changes

There is no behavioural changes
## Backwards compatibility

There are no backwards compatibility breaks

### CODE REVIEW

**Comment by jasonwynn10** [comment]
Aren't all these going to be removed eventually though?

**Comment by dktapps** [comment]
what gives you that idea?

**Comment by jasonwynn10** [comment]
Window ids dont exist in API 4

**Comment by DaPigGuy** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/network/mcpe/protocol/types/inventory/WindowTypes.php

**Comment by jasonwynn10** [comment]
Oh I'm wrong, my bad. 👍

**Comment by dktapps** [comment]
these are protocol constants, so I don't see why you would think that.

**Comment by dktapps** [comment]
closing and reopening to try and get travis to cooperate

**Pull request merged**
