### PR TITLE
Update Vector3

### PR DESCRIPTION
**Pull request by Frago9876543210**
## Introduction
This PR will simplify the work with Vector3

### API changes
Now you can change one of the coordinates without calling the class again.

e.g:
```php
$player->getPosition()->setY($player->y - 10);
```

### CODE REVIEW

**Comment by dktapps** [comment]
That won't work. getPosition() returns a new Position instance.

**Comment by jojoe77777** [comment]
Anything wrong with `setComponents($x, $y, $z)`?

**Comment by Frago9876543210** [comment]
@jojoe77777 you can not change only one of the coordinates.

**Comment by dktapps** [comment]
`$v->setComponents($v->x, $v->y - 10, $v->z);`

**Comment by Frago9876543210** [comment]
@dktapps you need to get x and z to set y.

**Comment by jojoe77777** [comment]
@Frago9876543210 which he just did in his example...

**Pull request closed without merging**
