### PR TITLE
added the possibility to overwrite BlockSerializer, BlockDeserializer, ItemSerializer

### PR DESCRIPTION
**Pull request by SenseiTarzan**

### CODE REVIEW

**Comment by SenseiTarzan** [comment]
@dktapps

**Comment by dktapps** [comment]
To be honest I don't see the use case for this. Overriding serializers is a sketchy hack anyway, and is a noisy-neighbour behaviour. Every time someone has asked for it, it's been for the same kind of XY problem case as we've previously seen with custom player classes and custom entity classes.

**Comment by SenseiTarzan** [comment]
> To be honest I don't see the use case for this. Overriding serializers is a sketchy hack anyway, and is a noisy-neighbour behaviour. Every time someone has asked for it, it's been for the same kind of XY problem case as we've previously seen with custom player classes and custom entity classes.

I made this because it was foreseen that if I don't allow this people can't overwrite their block giving there is a problem in the item give, it gives an update_block

**Comment by dktapps** [comment]
As I said, XY problem. /give has nothing to do with these serializers - that's the domain of StringToItemParser. And this code doesn't stop you from registering custom blocks.

**Comment by SenseiTarzan** [comment]
> As I said, XY problem. /give has nothing to do with these serializers - that's the domain of StringToItemParser. And this code doesn't stop you from registering custom blocks.

plus the change I made was something that was supposed to be deleted as a //TODO: REMOVE ME

**Comment by SenseiTarzan** [comment]
image

**Comment by SenseiTarzan** [comment]
I do not make any case of Hack it is just that in the BlockFactory we can overwrite and not on the Serializer and the Deserializer whereas it is essential

**Comment by SenseiTarzan** [comment]
I don't know why you're skeptical when it was planned

**Comment by SenseiTarzan** [comment]
in addition register the class-string while it is possible to set a single serialize or deserialize not typeId

**Comment by SenseiTarzan** [comment]
?

**Comment by dktapps** [comment]
Yes, I allowed for the possibility, and since realized that it doesn't make any sense. 

> I do not make any case of Hack it is just that in the BlockFactory we can overwrite and not on the Serializer and the Deserializer whereas it is essential

This is a bad argument. Overriding blocks via BlockFactory was also sketchy and wasn't properly supported.

**Comment by SenseiTarzan** [comment]
what do you want to do to make it better

**Comment by SenseiTarzan** [comment]
then why did you allow in the ItemDeserializer the overwrite

**Comment by dktapps** [comment]
> then why did you allow in the ItemDeserializer the overwrite

That's a bug. It's not supposed to allow that.

**Comment by SenseiTarzan** [comment]
the problem now is that the block can't be overwritten and that means that the overwrite variable in blockFactory is useless if the DeSerializer doesn't have the right block

**Comment by dktapps** [comment]
The mess around this has been cleaned up by https://github.com/pmmp/PocketMine-MP/commit/9621836e36b9a9bb8c3ce1d339871bd6a07d7cc1.

**Comment by SenseiTarzan** [comment]
If you block the overwrite option then a good majority of plugins are broken and that means you will have to add the option to add custom blocks

**Comment by SenseiTarzan** [comment]
So that's not to tell you that many are scaring away pmmp because it will no longer be possible to overwrite the blocks

**Comment by ShockedPlot7560** [comment]
Block IDs have changed under pocketmine 5. These are now runtime only unique ids, so even with an override it shouldn't be possible to change their values.

**Pull request closed without merging**
