### PR TITLE
Added Dockerfile

### LINKED ISSUE #928: Create Docker container for easier distribution
### Issue description
PMMP Team: I've created a docker image for PMMP that may be useful to include in the broader distribution. If you think its worth to have as part of the main distribution I can fork and submit a PR.

https://github.com/crscheid/pocketmine-mp

### Steps to reproduce the issue
None

### OS and versions
N/A

### Crashdump, backtrace or other files
N/A

### PR DESCRIPTION
**Pull request by SOF3**
## Introduction
Closes #928

## Discussion needed
The configuration currently only builds the following:
```
branch master -> pmmp/pocketmine-mp:dev
tag .* -> pmmp/pocketmine-mp:{sourceref}
tag .* -> pmmp/pocketmine-mp:latest
```

Should other branches be built?

## Follow-up
Advertise the docker repository `pmmp/pocketmine-mp` in README, etc.

### CODE REVIEW

**Comment by dktapps** [comment]
I wonder if we should make use of `apt` and system libraries here since we have them guaranteed available in this environment.

**Comment by SOF3** [comment]
Would using `apt` introduce inconvenience since we might have custom extensions?

**Comment by SOF3** [comment]
To minimize the maintenance cost, using the php;-build-scripts artifact is more preferrable, unless we no longer ship non-Docker builds.

**Comment by dktapps** [comment]
The maintenance cost of php-build-scripts is very high. This is why I suggested using system libraries inside the image.

**Comment by SOF3** [comment]
This docker image is not going to remove the maintenance cost of php-build-scripts as we are not deprecating the latter. Right now it only relies on the public API of the Jenkins server that is unlikely to change. I don't see how using system libraries would reduce maintenance cost.

**Pull request merged**
